#!/usr/bin/env python3
"""Generate bbts_wave9_data.json — BBTS AF brand expansion wave 9."""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).with_name("bbts_wave9_data.json")

def R(suf, name, sub, date, demand, msrp=None):
    row = [suf, name, sub, date, float(demand)]
    if msrp is not None:
        row.append(float(msrp))
    return row

def dates(y, m, n, step=1):
    out = []
    for _ in range(n):
        out.append(f"{y:04d}-{m:02d}-01")
        m += step
        while m > 12:
            m -= 12
            y += 1
    return out

def add(data, key, prefix, items, y, m, step, default_msrp):
    ds = dates(y, m, len(items), step)
    rows = []
    for i, it in enumerate(items):
        if len(it) == 4:
            name, sub, demand, msrp = it
        else:
            name, sub, demand = it
            msrp = default_msrp
        rows.append(R(f"{prefix}-{i+1:02d}", name, sub, max(ds[i], "1980-01-01"), demand, msrp))
    data[key] = rows

data: dict[str, list] = {}

# ========== NEW (12) ==========
# Mego — World's Greatest / retro AF reissues
add(data, "mego", "mg", [
    ("Superman", "WGSH", 1.5), ("Batman", "WGSH", 1.5), ("Robin", "WGSH", 1.4),
    ("Wonder Woman", "WGSH", 1.45), ("Aquaman", "WGSH", 1.35), ("Flash", "WGSH", 1.4),
    ("Green Lantern", "WGSH", 1.4), ("The Joker", "WGSH", 1.5), ("Penguin", "WGSH", 1.4),
    ("Riddler", "WGSH", 1.4), ("Catwoman", "WGSH", 1.45), ("Mr. Freeze", "WGSH", 1.35),
    ("Spider-Man", "Marvel", 1.5), ("Hulk", "Marvel", 1.45), ("Captain America", "Marvel", 1.45),
    ("Iron Man", "Marvel", 1.45), ("Thor", "Marvel", 1.4), ("Human Torch", "Marvel", 1.35),
    ("Thing", "Marvel", 1.4), ("Invisible Woman", "Marvel", 1.35), ("Mr. Fantastic", "Marvel", 1.35),
    ("Wolverine", "Marvel", 1.5), ("Cyclops", "Marvel", 1.4), ("Storm", "Marvel", 1.4),
    ("Star Trek Kirk", "Star Trek", 1.45), ("Star Trek Spock", "Star Trek", 1.45),
    ("Star Trek McCoy", "Star Trek", 1.35), ("Star Trek Uhura", "Star Trek", 1.35),
    ("Star Trek Scotty", "Star Trek", 1.35), ("Star Trek Sulu", "Star Trek", 1.3),
    ("Freddy Krueger", "Horror", 1.5), ("Jason Voorhees", "Horror", 1.5),
    ("Michael Myers", "Horror", 1.5), ("Leatherface", "Horror", 1.45),
    ("Chucky", "Horror", 1.45), ("Pennywise", "Horror", 1.5),
    ("Superman Chase", "Special", 1.55), ("Batman Chase", "Special", 1.55),
    ("Spider-Man Chase", "Special", 1.55), ("Joker Chase", "Special", 1.55),
    ("WGSH 2-Pack Heroes", "Special", 1.45, 45), ("WGSH 2-Pack Villains", "Special", 1.45, 45),
    ("Mego Body Male", "Bodies", 1.25, 20), ("Mego Body Female", "Bodies", 1.25, 20),
    ("Mego Retro Box Set", "Special", 1.5, 80),
], 2018, 1, 1, 22.99)

# World Box — 1/6 AF bodies / figures
add(data, "worldbox", "wb", [
    ("AT027 Male Body", "Bodies", 1.4, 90), ("AT028 Female Body", "Bodies", 1.4, 90),
    ("AT029 Athletic Male", "Bodies", 1.45, 95), ("AT030 Athletic Female", "Bodies", 1.45, 95),
    ("Head Sculpt Male A", "Heads", 1.35, 35), ("Head Sculpt Male B", "Heads", 1.35, 35),
    ("Head Sculpt Female A", "Heads", 1.35, 35), ("Head Sculpt Female B", "Heads", 1.35, 35),
    ("Military Operative", "Modern", 1.45, 160), ("SWAT Officer", "Modern", 1.4, 150),
    ("PMC Contractor", "Modern", 1.4, 155), ("Police Officer", "Modern", 1.35, 145),
    ("Samurai Warrior", "Historical", 1.5, 180), ("Ninja Assassin", "Historical", 1.45, 170),
    ("Viking Berserker", "Historical", 1.45, 175), ("Knight Templar", "Historical", 1.5, 185),
    ("Fantasy Warrior", "Fantasy", 1.4, 165), ("Elf Archer", "Fantasy", 1.4, 160),
    ("Orc Fighter", "Fantasy", 1.4, 165), ("Dark Mage", "Fantasy", 1.35, 155),
    ("Sci-Fi Trooper", "Sci-Fi", 1.4, 160), ("Android Agent", "Sci-Fi", 1.4, 155),
    ("Space Marine", "Sci-Fi", 1.45, 170), ("Cyber Assassin", "Sci-Fi", 1.4, 160),
    ("Male Body Suntan", "Bodies", 1.35, 92), ("Female Body Pale", "Bodies", 1.35, 92),
    ("Military Deluxe", "Special", 1.5, 190), ("Samurai Deluxe", "Special", 1.55, 210),
    ("Ninja Deluxe", "Special", 1.5, 195), ("SWAT Deluxe", "Special", 1.45, 175),
    ("Head Pack A", "Heads", 1.3, 60), ("Head Pack B", "Heads", 1.3, 60),
    ("Hand Pack Male", "Accessories", 1.25, 25), ("Hand Pack Female", "Accessories", 1.25, 25),
    ("Weapon Pack Modern", "Accessories", 1.3, 40), ("Weapon Pack Historical", "Accessories", 1.3, 40),
    ("Fantasy Deluxe", "Special", 1.45, 185), ("Sci-Fi Deluxe", "Special", 1.45, 180),
    ("Body Athletic Chrome", "Special", 1.4, 110), ("PMC Deluxe", "Special", 1.45, 180),
    ("Knight Deluxe", "Special", 1.5, 200), ("Elf Archer Deluxe", "Special", 1.45, 175),
    ("Android Deluxe", "Special", 1.45, 170), ("Cyber Assassin Neon", "Special", 1.4, 165),
    ("World Box Starter Set", "Special", 1.4, 220),
], 2017, 3, 2, 150)

# Kaustic Plastik — 1/6 historical AF
add(data, "kaustic", "kp", [
    ("Roman Legionary", "Roman Empire", 1.5), ("Roman Centurion", "Roman Empire", 1.55),
    ("Roman Praetorian", "Roman Empire", 1.5), ("Roman Standard Bearer", "Roman Empire", 1.45),
    ("Gladiator Murmillo", "Roman Empire", 1.5), ("Gladiator Retiarius", "Roman Empire", 1.45),
    ("Spartan Hoplite", "Greek", 1.55), ("Spartan King", "Greek", 1.55),
    ("Athenian Hoplite", "Greek", 1.45), ("Macedonian Companion", "Greek", 1.45),
    ("Viking Warrior", "Viking", 1.5), ("Viking Jarl", "Viking", 1.55),
    ("Viking Shieldmaiden", "Viking", 1.5), ("Viking Berserker", "Viking", 1.5),
    ("Celtic Warrior", "Celtic", 1.4), ("Celtic Chieftain", "Celtic", 1.45),
    ("Medieval Knight", "Medieval", 1.5), ("Teutonic Knight", "Medieval", 1.5),
    ("Templar Knight", "Medieval", 1.55), ("Hospitaller", "Medieval", 1.45),
    ("WWII German Infantry", "WWII", 1.4), ("WWII US Paratrooper", "WWII", 1.45),
    ("WWII British Commando", "WWII", 1.45), ("WWII Soviet Sniper", "WWII", 1.4),
    ("Roman Deluxe", "Special", 1.55), ("Spartan Deluxe", "Special", 1.55),
    ("Viking Deluxe", "Special", 1.55), ("Templar Deluxe", "Special", 1.55),
    ("Gladiator Deluxe", "Special", 1.5), ("Knight Deluxe", "Special", 1.5),
    ("WWII US Deluxe", "Special", 1.5), ("WWII German Deluxe", "Special", 1.45),
    ("Celtic Deluxe", "Special", 1.45), ("Praetorian Deluxe", "Special", 1.55),
    ("Roman Cavalry", "Roman Empire", 1.5), ("Greek Archer", "Greek", 1.4),
    ("Viking Archer", "Viking", 1.4), ("Medieval Archer", "Medieval", 1.4),
    ("Roman Optio", "Roman Empire", 1.45), ("Spartan Officer", "Greek", 1.5),
    ("Viking Raider", "Viking", 1.45), ("Black Knight", "Medieval", 1.5),
    ("WWII Medic", "WWII", 1.35), ("WWII Officer", "WWII", 1.4),
    ("Kaustic Accessory Pack", "Special", 1.25, 45),
], 2015, 4, 2, 200)

# POP Toys — 1/6 historical / fantasy
add(data, "poptoys", "pt", [
    ("EX001 Spartan Warrior", "EX Series", 1.5), ("EX002 Spartan King", "EX Series", 1.55),
    ("EX003 Roman Legionary", "EX Series", 1.45), ("EX004 Roman Centurion", "EX Series", 1.5),
    ("EX005 Viking Warrior", "EX Series", 1.5), ("EX006 Viking Jarl", "EX Series", 1.55),
    ("EX007 Knight Templar", "EX Series", 1.55), ("EX008 Teutonic Knight", "EX Series", 1.5),
    ("EX009 Samurai General", "EX Series", 1.55), ("EX010 Samurai Ashigaru", "EX Series", 1.4),
    ("EX011 Ninja Shadow", "EX Series", 1.5), ("EX012 Shaolin Monk", "EX Series", 1.4),
    ("EX013 Egyptian Pharaoh", "EX Series", 1.5), ("EX014 Egyptian Guard", "EX Series", 1.35),
    ("EX015 Persian Immortal", "EX Series", 1.45), ("EX016 Macedonian", "EX Series", 1.4),
    ("EX017 Gladiator", "EX Series", 1.5), ("EX018 Amazon Warrior", "EX Series", 1.45),
    ("EX019 Dark Knight", "EX Series", 1.5), ("EX020 Elf Archer", "EX Series", 1.45),
    ("EX001 Deluxe", "Special", 1.55), ("EX002 Deluxe", "Special", 1.55),
    ("EX005 Deluxe", "Special", 1.55), ("EX007 Deluxe", "Special", 1.55),
    ("EX009 Deluxe", "Special", 1.55), ("EX011 Deluxe", "Special", 1.55),
    ("EX013 Deluxe", "Special", 1.5), ("EX017 Deluxe", "Special", 1.5),
    ("EX021 Pirate Captain", "EX Series", 1.45), ("EX022 Pirate Crew", "EX Series", 1.35),
    ("EX023 Cowboy Gunslinger", "Western", 1.4), ("EX024 Native Warrior", "Western", 1.4),
    ("EX025 WWII US Ranger", "WWII", 1.45), ("EX026 WWII German", "WWII", 1.4),
    ("EX027 Modern SEAL", "Modern", 1.5), ("EX028 Modern Delta", "Modern", 1.5),
    ("EX029 Fantasy Wizard", "Fantasy", 1.4), ("EX030 Fantasy Orc", "Fantasy", 1.4),
    ("Weapon Pack A", "Accessories", 1.25, 40), ("Weapon Pack B", "Accessories", 1.25, 40),
    ("Head Pack Historical", "Accessories", 1.3, 50), ("Armor Pack Knight", "Accessories", 1.35, 70),
    ("EX Samurai Chrome", "Special", 1.55), ("EX Ninja Ghost", "Special", 1.5),
    ("EX Spartan Chrome", "Special", 1.55),
], 2016, 5, 2, 190)

# Devil Toys — designer / street AF
add(data, "deviltoys", "dv", [
    ("Devilman Classic", "Devilman", 1.55), ("Devilman Black", "Devilman", 1.55),
    ("Devilman White", "Devilman", 1.5), ("Devilman Red", "Devilman", 1.5),
    ("Street Demon A", "Street", 1.4), ("Street Demon B", "Street", 1.4),
    ("Street Demon C", "Street", 1.35), ("Street Demon D", "Street", 1.35),
    ("Punk Assassin", "Street", 1.4), ("Punk Boss", "Street", 1.45),
    ("Cyber Devil", "Cyber", 1.5), ("Cyber Angel", "Cyber", 1.45),
    ("Cyber Soldier", "Cyber", 1.4), ("Cyber Hunter", "Cyber", 1.4),
    ("Oni Mask Red", "Oni", 1.5), ("Oni Mask Blue", "Oni", 1.45),
    ("Oni Mask Black", "Oni", 1.5), ("Oni Mask Gold", "Oni", 1.55),
    ("Designer Hero A", "Designer", 1.4), ("Designer Hero B", "Designer", 1.4),
    ("Designer Villain A", "Designer", 1.4), ("Designer Villain B", "Designer", 1.4),
    ("Devilman Deluxe", "Special", 1.55), ("Devilman Chrome", "Special", 1.55),
    ("Street Demon Deluxe", "Special", 1.45), ("Cyber Devil Deluxe", "Special", 1.5),
    ("Oni Mask Deluxe", "Special", 1.55), ("Punk Boss Deluxe", "Special", 1.5),
    ("Mini Devilman", "Mini", 1.3, 40), ("Mini Street Demon", "Mini", 1.25, 35),
    ("Mini Oni", "Mini", 1.3, 40), ("Mini Cyber", "Mini", 1.25, 35),
    ("Devilman Clear", "Special", 1.5), ("Street Neon", "Special", 1.4),
    ("Cyber Neon", "Special", 1.45), ("Oni Ghost", "Special", 1.5),
    ("Designer Chrome", "Special", 1.45), ("Designer Clear", "Special", 1.4),
    ("Devilman Battle Damaged", "Special", 1.5), ("Street Pack", "Special", 1.4, 120),
    ("Cyber Pack", "Special", 1.4, 130), ("Oni Pack", "Special", 1.45, 140),
    ("Devil Toys Starter", "Special", 1.35, 90), ("Accessory Pack", "Special", 1.25, 35),
    ("Devilman Glow", "Special", 1.55),
], 2018, 2, 2, 120)

# King Arts — diecast metal AF
add(data, "kingarts", "ka", [
    ("DFS001 Iron Man Mark III", "Diecast", 1.55, 280), ("DFS002 Iron Man Mark VII", "Diecast", 1.55, 290),
    ("DFS003 Iron Man Mark XLII", "Diecast", 1.55, 300), ("DFS004 Iron Man Mark XLIII", "Diecast", 1.5, 290),
    ("DFS005 Iron Man Mark XLV", "Diecast", 1.55, 310), ("DFS006 Iron Man Mark L", "Diecast", 1.55, 320),
    ("DFS007 War Machine", "Diecast", 1.5, 280), ("DFS008 Iron Patriot", "Diecast", 1.45, 270),
    ("DFS009 Hulkbuster", "Diecast", 1.55, 450), ("DFS010 Iron Man Classic", "Diecast", 1.5, 260),
    ("DFS011 Batman Armored", "Diecast", 1.55, 300), ("DFS012 Batman Classic", "Diecast", 1.5, 270),
    ("DFS013 Superman", "Diecast", 1.5, 260), ("DFS014 Captain America", "Diecast", 1.45, 240),
    ("DFS015 Thor", "Diecast", 1.45, 250), ("DFS016 Hulk", "Diecast", 1.5, 280),
    ("DFS017 Spider-Man", "Diecast", 1.5, 250), ("DFS018 Venom", "Diecast", 1.5, 260),
    ("DFS019 Black Panther", "Diecast", 1.5, 270), ("DFS020 Doctor Strange", "Diecast", 1.45, 240),
    ("DFS Iron Man Chrome", "Special", 1.55, 340), ("DFS War Machine Chrome", "Special", 1.55, 320),
    ("DFS Batman Chrome", "Special", 1.55, 330), ("DFS Hulkbuster Deluxe", "Special", 1.55, 500),
    ("DFS Iron Man Clear", "Special", 1.5, 310), ("DFS Spider-Man Symbiote", "Special", 1.55, 280),
    ("DFS Accessories Pack A", "Accessories", 1.3, 60), ("DFS Accessories Pack B", "Accessories", 1.3, 60),
    ("DFS Stand Pack", "Accessories", 1.25, 40), ("DFS Effect Pack", "Accessories", 1.3, 55),
    ("DFS Iron Man Mark I", "Diecast", 1.45, 250), ("DFS Iron Man Mark II", "Diecast", 1.45, 255),
    ("DFS Iron Man Mark IV", "Diecast", 1.5, 275), ("DFS Iron Man Mark V", "Diecast", 1.5, 280),
    ("DFS Iron Man Mark VI", "Diecast", 1.5, 285), ("DFS Iron Man Mark XVII", "Diecast", 1.45, 270),
    ("DFS Rescue Armor", "Diecast", 1.5, 290), ("DFS Iron Spider", "Diecast", 1.5, 275),
    ("DFS Batman Battle Damaged", "Special", 1.5, 310), ("DFS Superman Chrome", "Special", 1.5, 290),
    ("DFS Cap Chromed", "Special", 1.45, 260), ("DFS Thor Stormbreaker", "Special", 1.5, 280),
    ("DFS Black Panther Chrome", "Special", 1.55, 300), ("DFS Venom Chrome", "Special", 1.55, 290),
    ("DFS Iron Man Endgame", "Special", 1.55, 330),
], 2014, 6, 2, 280)

# JT Studio — 1/6 licensed / movie AF
add(data, "jtstudio", "jt", [
    ("JT001 Movie Hero A", "Movie", 1.5), ("JT002 Movie Hero B", "Movie", 1.45),
    ("JT003 Movie Villain A", "Movie", 1.5), ("JT004 Movie Villain B", "Movie", 1.45),
    ("JT005 Action Star A", "Celebrity", 1.45), ("JT006 Action Star B", "Celebrity", 1.45),
    ("JT007 Action Star C", "Celebrity", 1.4), ("JT008 Action Star D", "Celebrity", 1.4),
    ("JT009 Martial Artist A", "Martial Arts", 1.5), ("JT010 Martial Artist B", "Martial Arts", 1.5),
    ("JT011 Martial Artist C", "Martial Arts", 1.45), ("JT012 Martial Artist D", "Martial Arts", 1.45),
    ("JT013 Cop Classic", "Crime", 1.4), ("JT014 Detective", "Crime", 1.4),
    ("JT015 Gangster Boss", "Crime", 1.45), ("JT016 Hitman", "Crime", 1.4),
    ("JT017 Sci-Fi Soldier", "Sci-Fi", 1.45), ("JT018 Sci-Fi Captain", "Sci-Fi", 1.45),
    ("JT019 Horror Icon A", "Horror", 1.5), ("JT020 Horror Icon B", "Horror", 1.5),
    ("JT001 Deluxe", "Special", 1.55), ("JT003 Deluxe", "Special", 1.55),
    ("JT009 Deluxe", "Special", 1.55), ("JT019 Deluxe", "Special", 1.55),
    ("JT021 Western Gunslinger", "Western", 1.4), ("JT022 Western Outlaw", "Western", 1.4),
    ("JT023 Sports Legend A", "Sports", 1.35), ("JT024 Sports Legend B", "Sports", 1.35),
    ("JT025 Musician Icon A", "Music", 1.4), ("JT026 Musician Icon B", "Music", 1.4),
    ("JT027 Historical Figure A", "Historical", 1.4), ("JT028 Historical Figure B", "Historical", 1.4),
    ("JT029 Fantasy Warrior", "Fantasy", 1.45), ("JT030 Fantasy Mage", "Fantasy", 1.4),
    ("Head Sculpt Pack A", "Accessories", 1.3, 55), ("Head Sculpt Pack B", "Accessories", 1.3, 55),
    ("Outfit Pack Modern", "Accessories", 1.35, 70), ("Outfit Pack Period", "Accessories", 1.35, 70),
    ("JT Movie Chrome", "Special", 1.5), ("JT Martial Chrome", "Special", 1.5),
    ("JT Horror Glow", "Special", 1.5), ("JT Sci-Fi Neon", "Special", 1.45),
    ("JT Celebrity Deluxe", "Special", 1.5), ("JT Crime Deluxe", "Special", 1.45),
    ("JT Studio Box Set", "Special", 1.45, 350),
], 2016, 1, 2, 220)

# Art Spirits — Sonic / mecha AF
add(data, "artspirits", "as9", [
    ("Sonic the Hedgehog", "Sonic", 1.55), ("Shadow the Hedgehog", "Sonic", 1.55),
    ("Silver the Hedgehog", "Sonic", 1.45), ("Knuckles", "Sonic", 1.5),
    ("Tails", "Sonic", 1.45), ("Amy Rose", "Sonic", 1.4),
    ("Metal Sonic", "Sonic", 1.5), ("Dr. Eggman", "Sonic", 1.45),
    ("Sonic Adventure", "Sonic", 1.5), ("Sonic Boom", "Sonic", 1.4),
    ("Sonic Movie", "Sonic", 1.5), ("Shadow Movie", "Sonic", 1.5),
    ("Mecha Godzilla Spirit", "Mecha", 1.55), ("Gundam Spirit Homage", "Mecha", 1.5),
    ("Mazinger Spirit", "Mecha", 1.5), ("Getter Spirit", "Mecha", 1.45),
    ("Ultraman Spirit", "Tokusatsu", 1.5), ("Ultraseven Spirit", "Tokusatsu", 1.45),
    ("Kamen Rider Spirit", "Tokusatsu", 1.5), ("Godzilla Spirit", "Tokusatsu", 1.5),
    ("Sonic Chrome", "Special", 1.55), ("Shadow Chrome", "Special", 1.55),
    ("Metal Sonic Chrome", "Special", 1.55), ("Sonic Clear", "Special", 1.5),
    ("Sonic Deluxe", "Special", 1.55), ("Shadow Deluxe", "Special", 1.55),
    ("Mecha Deluxe", "Special", 1.55), ("Ultraman Deluxe", "Special", 1.55),
    ("Sonic Mini", "Mini", 1.3, 35), ("Shadow Mini", "Mini", 1.3, 35),
    ("Knuckles Mini", "Mini", 1.25, 32), ("Tails Mini", "Mini", 1.25, 32),
    ("Sonic Glow", "Special", 1.5), ("Shadow Glow", "Special", 1.5),
    ("Metal Sonic Neon", "Special", 1.5), ("Eggman Deluxe", "Special", 1.45),
    ("Sonic Movie Deluxe", "Special", 1.55), ("Shadow Movie Deluxe", "Special", 1.55),
    ("Mecha Godzilla Chrome", "Special", 1.55), ("Gundam Spirit Chrome", "Special", 1.5),
    ("Tokusatsu Pack", "Special", 1.45, 200), ("Sonic Pack", "Special", 1.5, 180),
    ("Art Spirits Stand", "Accessories", 1.2, 25), ("Effect Parts Pack", "Accessories", 1.25, 40),
    ("Sonic Super Form", "Special", 1.55),
], 2017, 4, 2, 95)

# Art Storm — mecha AF
add(data, "artstorm", "ast", [
    ("Sonic the Hedgehog Art Storm", "Sonic", 1.5), ("Shadow Art Storm", "Sonic", 1.5),
    ("Metal Sonic Art Storm", "Sonic", 1.5), ("Knuckles Art Storm", "Sonic", 1.45),
    ("Mecha Collection A", "Mecha", 1.5), ("Mecha Collection B", "Mecha", 1.45),
    ("Mecha Collection C", "Mecha", 1.45), ("Mecha Collection D", "Mecha", 1.4),
    ("Mecha Collection E", "Mecha", 1.4), ("Mecha Collection F", "Mecha", 1.4),
    ("Tokusatsu Hero A", "Tokusatsu", 1.5), ("Tokusatsu Hero B", "Tokusatsu", 1.45),
    ("Tokusatsu Hero C", "Tokusatsu", 1.45), ("Tokusatsu Monster A", "Tokusatsu", 1.4),
    ("Tokusatsu Monster B", "Tokusatsu", 1.4), ("Tokusatsu Monster C", "Tokusatsu", 1.35),
    ("Flying Mecha A", "Mecha", 1.45), ("Flying Mecha B", "Mecha", 1.45),
    ("Ground Mecha A", "Mecha", 1.4), ("Ground Mecha B", "Mecha", 1.4),
    ("Sonic Art Storm Chrome", "Special", 1.55), ("Shadow Art Storm Chrome", "Special", 1.55),
    ("Mecha A Chrome", "Special", 1.5), ("Mecha B Clear", "Special", 1.45),
    ("Tokusatsu Hero Deluxe", "Special", 1.55), ("Tokusatsu Monster Deluxe", "Special", 1.45),
    ("Mini Mecha A", "Mini", 1.25, 40), ("Mini Mecha B", "Mini", 1.25, 40),
    ("Mini Sonic", "Mini", 1.3, 35), ("Mini Shadow", "Mini", 1.3, 35),
    ("Flying Mecha Deluxe", "Special", 1.5), ("Ground Mecha Deluxe", "Special", 1.45),
    ("Art Storm Combo Pack", "Special", 1.45, 220), ("Effect Pack Storm", "Accessories", 1.25, 45),
    ("Mecha C Metallic", "Special", 1.45), ("Mecha D Neon", "Special", 1.4),
    ("Tokusatsu Glow", "Special", 1.45), ("Sonic Super Art Storm", "Special", 1.55),
    ("Metal Sonic Neon", "Special", 1.5), ("Knuckles Chrome", "Special", 1.45),
    ("Mecha E Battle Damaged", "Special", 1.4), ("Mecha F Clear", "Special", 1.4),
    ("Stand Pack Storm", "Accessories", 1.2, 30), ("Weapon Pack Storm", "Accessories", 1.25, 40),
    ("Art Storm Starter", "Special", 1.35, 100),
], 2018, 5, 2, 100)

# 52Toys — BeastBOX / transformable AF
add(data, "fiftytwo", "ft", [
    ("BeastBOX BB-01 Lion", "BeastBOX", 1.5), ("BeastBOX BB-02 Tiger", "BeastBOX", 1.45),
    ("BeastBOX BB-03 Wolf", "BeastBOX", 1.45), ("BeastBOX BB-04 Eagle", "BeastBOX", 1.45),
    ("BeastBOX BB-05 Rhino", "BeastBOX", 1.4), ("BeastBOX BB-06 Gorilla", "BeastBOX", 1.45),
    ("BeastBOX BB-07 Shark", "BeastBOX", 1.4), ("BeastBOX BB-08 Snake", "BeastBOX", 1.35),
    ("BeastBOX BB-09 Scorpion", "BeastBOX", 1.4), ("BeastBOX BB-10 Raptor", "BeastBOX", 1.5),
    ("BeastBOX BB-11 Panther", "BeastBOX", 1.45), ("BeastBOX BB-12 Bear", "BeastBOX", 1.4),
    ("MegaBOX MB-01", "MegaBOX", 1.5), ("MegaBOX MB-02", "MegaBOX", 1.45),
    ("MegaBOX MB-03", "MegaBOX", 1.45), ("MegaBOX MB-04", "MegaBOX", 1.4),
    ("MegaBOX MB-05", "MegaBOX", 1.4), ("MegaBOX MB-06", "MegaBOX", 1.4),
    ("BB Lion Chrome", "Special", 1.55), ("BB Tiger Desert", "Special", 1.45),
    ("BB Wolf Night", "Special", 1.45), ("BB Eagle Clear", "Special", 1.45),
    ("BB Raptor Metallic", "Special", 1.55), ("BB Panther Ghost", "Special", 1.45),
    ("MB-01 Chrome", "Special", 1.55), ("MB-02 Clear", "Special", 1.45),
    ("Mini Beast Lion", "Mini", 1.25, 25), ("Mini Beast Tiger", "Mini", 1.2, 22),
    ("Mini Beast Wolf", "Mini", 1.2, 22), ("Mini Beast Eagle", "Mini", 1.2, 22),
    ("BB Combiner A", "Combiner", 1.35, 50), ("BB Combiner B", "Combiner", 1.3, 48),
    ("BB Combiner C", "Combiner", 1.3, 48), ("BB Combiner Complete", "Combiner", 1.55, 180),
    ("BB Upgrade Pack", "Special", 1.25, 30), ("MB Upgrade Pack", "Special", 1.25, 35),
    ("BB Shark Chrome", "Special", 1.45), ("BB Gorilla Black", "Special", 1.45),
    ("BB Snake Neon", "Special", 1.35), ("BB Scorpion Metallic", "Special", 1.4),
    ("BB Bear Winter", "Special", 1.4), ("MB-03 Metallic", "Special", 1.45),
    ("MB-04 Neon", "Special", 1.4), ("52Toys Display Stand", "Accessories", 1.2, 20),
    ("BeastBOX Starter Set", "Special", 1.4, 90),
], 2019, 1, 1, 55)

# Action Toys — anime / mecha AF
add(data, "actiontoys", "at", [
    ("ES Gokin Mazinger Z", "ES Gokin", 1.55), ("ES Gokin Great Mazinger", "ES Gokin", 1.5),
    ("ES Gokin Grendizer", "ES Gokin", 1.55), ("ES Gokin Getter 1", "ES Gokin", 1.5),
    ("ES Gokin Getter 2", "ES Gokin", 1.45), ("ES Gokin Getter 3", "ES Gokin", 1.45),
    ("ES Gokin Jeeg", "ES Gokin", 1.5), ("ES Gokin Raideen", "ES Gokin", 1.5),
    ("Mini Action Mazinger", "Mini Action", 1.4), ("Mini Action Grendizer", "Mini Action", 1.4),
    ("Mini Action Getter", "Mini Action", 1.35), ("Mini Action Jeeg", "Mini Action", 1.35),
    ("Hero Action Ultraman", "Hero Action", 1.5), ("Hero Action Ultraseven", "Hero Action", 1.45),
    ("Hero Action Ultraman Tiga", "Hero Action", 1.45), ("Hero Action Ultraman Gaia", "Hero Action", 1.4),
    ("Hero Action Kamen Rider", "Hero Action", 1.5), ("Hero Action Kamen Rider Black", "Hero Action", 1.5),
    ("ES Gokin Mazinger Chrome", "Special", 1.55), ("ES Gokin Grendizer Gold", "Special", 1.55),
    ("ES Gokin Getter Deluxe", "Special", 1.55), ("ES Gokin Jeeg Deluxe", "Special", 1.55),
    ("Mini Action Chrome", "Special", 1.45), ("Hero Action Deluxe", "Special", 1.55),
    ("ES Gokin Clear", "Special", 1.5), ("ES Gokin Battle Damaged", "Special", 1.5),
    ("Hero Action Glow", "Special", 1.5), ("Mini Action Pack", "Special", 1.4, 80),
    ("ES Gokin Effect Parts", "Accessories", 1.3, 45), ("Hero Action Stand", "Accessories", 1.2, 25),
    ("ES Gokin Mazinger Black", "Special", 1.55), ("ES Gokin Great Mazinger Black", "Special", 1.5),
    ("Hero Action Alien Baltan", "Hero Action", 1.4), ("Hero Action Alien Zetton", "Hero Action", 1.4),
    ("Mini Action Raideen", "Mini Action", 1.35), ("Mini Action Ultraman", "Mini Action", 1.35),
    ("ES Gokin Combiner A", "Combiner", 1.4, 70), ("ES Gokin Combiner B", "Combiner", 1.35, 65),
    ("ES Gokin Combiner Complete", "Combiner", 1.55, 250), ("Action Toys Starter", "Special", 1.35, 90),
    ("ES Gokin Weapon Pack", "Accessories", 1.25, 40), ("Hero Action Weapon Pack", "Accessories", 1.25, 40),
    ("ES Gokin Grendizer Clear", "Special", 1.55), ("Hero Action Ultraman Chrome", "Special", 1.55),
    ("Mini Action Glow", "Special", 1.4),
], 2015, 3, 2, 110)

# Underverse — 1/12 AF
add(data, "underverse", "uv", [
    ("UV001 Operative A", "1/12 Series", 1.4), ("UV002 Operative B", "1/12 Series", 1.4),
    ("UV003 Operative C", "1/12 Series", 1.35), ("UV004 Operative D", "1/12 Series", 1.35),
    ("UV005 Spec Ops A", "1/12 Series", 1.45), ("UV006 Spec Ops B", "1/12 Series", 1.45),
    ("UV007 Spec Ops C", "1/12 Series", 1.4), ("UV008 Spec Ops D", "1/12 Series", 1.4),
    ("UV009 Sci-Fi Trooper", "1/12 Sci-Fi", 1.45), ("UV010 Sci-Fi Captain", "1/12 Sci-Fi", 1.45),
    ("UV011 Sci-Fi Android", "1/12 Sci-Fi", 1.4), ("UV012 Sci-Fi Hunter", "1/12 Sci-Fi", 1.4),
    ("UV013 Fantasy Knight", "1/12 Fantasy", 1.45), ("UV014 Fantasy Archer", "1/12 Fantasy", 1.4),
    ("UV015 Fantasy Mage", "1/12 Fantasy", 1.4), ("UV016 Fantasy Orc", "1/12 Fantasy", 1.4),
    ("UV017 Street Fighter A", "1/12 Street", 1.4), ("UV018 Street Fighter B", "1/12 Street", 1.4),
    ("UV019 Street Boss", "1/12 Street", 1.45), ("UV020 Street Assassin", "1/12 Street", 1.4),
    ("UV001 Deluxe", "Special", 1.5), ("UV005 Deluxe", "Special", 1.55),
    ("UV009 Deluxe", "Special", 1.5), ("UV013 Deluxe", "Special", 1.5),
    ("UV021 Body Male", "Bodies", 1.3, 35), ("UV022 Body Female", "Bodies", 1.3, 35),
    ("UV023 Head Pack A", "Accessories", 1.25, 20), ("UV024 Head Pack B", "Accessories", 1.25, 20),
    ("UV025 Weapon Pack Modern", "Accessories", 1.3, 25), ("UV026 Weapon Pack Fantasy", "Accessories", 1.3, 25),
    ("UV Spec Ops Chrome", "Special", 1.5), ("UV Sci-Fi Neon", "Special", 1.45),
    ("UV Fantasy Chrome", "Special", 1.45), ("UV Street Neon", "Special", 1.4),
    ("UV Operative Clear", "Special", 1.4), ("UV Spec Ops Night", "Special", 1.45),
    ("UV Sci-Fi Battle Damaged", "Special", 1.45), ("UV Fantasy Glow", "Special", 1.4),
    ("UV Starter Set", "Special", 1.35, 80), ("UV Display Stand", "Accessories", 1.15, 15),
    ("UV027 Female Operative", "1/12 Series", 1.4), ("UV028 Female Spec Ops", "1/12 Series", 1.45),
    ("UV029 Female Sci-Fi", "1/12 Sci-Fi", 1.4), ("UV030 Female Fantasy", "1/12 Fantasy", 1.4),
    ("UV Female Deluxe", "Special", 1.5),
], 2020, 2, 1, 55)

# ========== DENSIFY (14) ==========
add(data, "neca", "nc", [
    ("Ultimate Michelangelo", "TMNT", 1.5), ("Ultimate Leonardo", "TMNT", 1.5),
    ("Ultimate Donatello", "TMNT", 1.45), ("Ultimate Raphael", "TMNT", 1.5),
    ("Ultimate Shredder", "TMNT", 1.55), ("Ultimate Splinter", "TMNT", 1.45),
    ("Ultimate Casey Jones", "TMNT", 1.4), ("Ultimate April O'Neil", "TMNT", 1.35),
    ("Ultimate Alien Warrior", "Aliens", 1.55), ("Ultimate Alien Queen", "Aliens", 1.55),
    ("Ultimate Predator", "Predator", 1.55), ("Ultimate City Hunter", "Predator", 1.5),
    ("Ultimate Freddy", "Horror", 1.5), ("Ultimate Jason", "Horror", 1.5),
    ("Ultimate Myers", "Horror", 1.5), ("Ultimate Leatherface", "Horror", 1.45),
    ("Ultimate Chucky", "Horror", 1.45), ("Ultimate Pennywise", "Horror", 1.55),
    ("Ultimate Ash", "Horror", 1.5), ("Ultimate Pinhead", "Horror", 1.5),
    ("Ultimate RoboCop", "Movie", 1.5), ("Ultimate T-800", "Movie", 1.55),
    ("Ultimate T-1000", "Movie", 1.55), ("Ultimate Deckard", "Movie", 1.45),
    ("Ultimate Batman 89", "DC", 1.5), ("Ultimate Joker 89", "DC", 1.55),
    ("Ultimate TMNT Foot Soldier", "TMNT", 1.35), ("Ultimate Krang", "TMNT", 1.5),
    ("Ultimate Bebop", "TMNT", 1.4), ("Ultimate Rocksteady", "TMNT", 1.4),
    ("Ultimate Alien Chestburster", "Aliens", 1.4), ("Ultimate Dog Alien", "Aliens", 1.45),
    ("Ultimate Jungle Hunter", "Predator", 1.55), ("Ultimate Elder Predator", "Predator", 1.5),
    ("Ultimate Ghostface", "Horror", 1.45), ("Ultimate Art the Clown", "Horror", 1.5),
    ("Ultimate Universal Monster Dracula", "Universal", 1.45), ("Ultimate Frankenstein", "Universal", 1.45),
    ("Ultimate Wolfman", "Universal", 1.4), ("Ultimate Mummy", "Universal", 1.4),
    ("Ultimate Creature Black Lagoon", "Universal", 1.45), ("Ultimate Bride of Frankenstein", "Universal", 1.45),
    ("Ultimate Godzilla 2003", "Godzilla", 1.5), ("Ultimate King Kong", "Godzilla", 1.5),
    ("Ultimate Them!", "Horror", 1.35),
], 2018, 1, 1, 35)

add(data, "super7", "s7", [
    ("ULTIMATES He-Man", "ULTIMATES!", 1.55), ("ULTIMATES Skeletor", "ULTIMATES!", 1.55),
    ("ULTIMATES Teela", "ULTIMATES!", 1.45), ("ULTIMATES Man-At-Arms", "ULTIMATES!", 1.45),
    ("ULTIMATES Evil-Lyn", "ULTIMATES!", 1.5), ("ULTIMATES Beast Man", "ULTIMATES!", 1.45),
    ("ULTIMATES Stratos", "ULTIMATES!", 1.4), ("ULTIMATES Mer-Man", "ULTIMATES!", 1.4),
    ("ULTIMATES Trap Jaw", "ULTIMATES!", 1.45), ("ULTIMATES Tri-Klops", "ULTIMATES!", 1.4),
    ("ULTIMATES Hordak", "ULTIMATES!", 1.5), ("ULTIMATES She-Ra", "ULTIMATES!", 1.5),
    ("ULTIMATES Snake Eyes", "ULTIMATES!", 1.5), ("ULTIMATES Cobra Commander", "ULTIMATES!", 1.55),
    ("ULTIMATES Storm Shadow", "ULTIMATES!", 1.5), ("ULTIMATES Destro", "ULTIMATES!", 1.5),
    ("ReAction He-Man", "ReAction", 1.35), ("ReAction Skeletor", "ReAction", 1.35),
    ("ReAction Snake Eyes", "ReAction", 1.35), ("ReAction Cobra Commander", "ReAction", 1.4),
    ("ReAction Alien", "ReAction", 1.4), ("ReAction Predator", "ReAction", 1.4),
    ("ReAction RoboCop", "ReAction", 1.35), ("ReAction T-800", "ReAction", 1.4),
    ("ULTIMATES Optimus", "ULTIMATES!", 1.55), ("ULTIMATES Megatron", "ULTIMATES!", 1.55),
    ("ULTIMATES Bumblebee", "ULTIMATES!", 1.45), ("ULTIMATES Starscream", "ULTIMATES!", 1.45),
    ("ULTIMATES ThunderCats Lion-O", "ULTIMATES!", 1.5), ("ULTIMATES Mumm-Ra", "ULTIMATES!", 1.55),
    ("ULTIMATES SilverHawks", "ULTIMATES!", 1.4), ("ULTIMATES Voltron", "ULTIMATES!", 1.55),
    ("ReAction ThunderCats", "ReAction", 1.35), ("ReAction Voltron", "ReAction", 1.4),
    ("ULTIMATES He-Man Soft Goods", "Special", 1.55), ("ULTIMATES Skeletor Soft Goods", "Special", 1.55),
    ("ULTIMATES Snake Eyes Soft Goods", "Special", 1.55), ("ULTIMATES Optimus Soft Goods", "Special", 1.55),
    ("ReAction Clear He-Man", "Special", 1.4), ("ReAction Glow Skeletor", "Special", 1.4),
    ("ULTIMATES Battle Cat", "ULTIMATES!", 1.5), ("ULTIMATES Panthor", "ULTIMATES!", 1.5),
    ("ULTIMATES Catra", "ULTIMATES!", 1.5), ("ULTIMATES Orko", "ULTIMATES!", 1.4),
    ("ULTIMATES King Hiss", "ULTIMATES!", 1.5),
], 2019, 2, 1, 55)

add(data, "threezero", "tz", [
    ("DLX Iron Man Mark 85", "DLX", 1.55), ("DLX Iron Man Mark 50", "DLX", 1.55),
    ("DLX War Machine", "DLX", 1.5), ("DLX Spider-Man", "DLX", 1.5),
    ("DLX Batman", "DLX", 1.55), ("DLX Superman", "DLX", 1.5),
    ("FigZero Eren Yeager", "FigZero", 1.5), ("FigZero Mikasa", "FigZero", 1.5),
    ("FigZero Levi", "FigZero", 1.55), ("FigZero Armored Titan", "FigZero", 1.55),
    ("FigZero Attack Titan", "FigZero", 1.55), ("FigZero Colossal Titan", "FigZero", 1.5),
    ("DLX Optimus Prime", "DLX", 1.55), ("DLX Megatron", "DLX", 1.55),
    ("DLX Bumblebee", "DLX", 1.5), ("DLX Soundwave", "DLX", 1.5),
    ("FigZero Guts", "FigZero", 1.55), ("FigZero Griffith", "FigZero", 1.5),
    ("FigZero Casca", "FigZero", 1.45), ("FigZero Skull Knight", "FigZero", 1.55),
    ("DLX RoboCop", "DLX", 1.5), ("DLX T-800", "DLX", 1.55),
    ("DLX Alien", "DLX", 1.55), ("DLX Predator", "DLX", 1.55),
    ("FigZero Naruto", "FigZero", 1.5), ("FigZero Sasuke", "FigZero", 1.5),
    ("FigZero Kakashi", "FigZero", 1.45), ("FigZero Itachi", "FigZero", 1.5),
    ("DLX Iron Man Chrome", "Special", 1.55), ("DLX Batman Chrome", "Special", 1.55),
    ("FigZero Levi Deluxe", "Special", 1.55), ("FigZero Guts Deluxe", "Special", 1.55),
    ("DLX Optimus Chrome", "Special", 1.55), ("DLX Megatron Chrome", "Special", 1.55),
    ("FigZero Eren Deluxe", "Special", 1.55), ("FigZero Mikasa Deluxe", "Special", 1.5),
    ("DLX Spider-Man Symbiote", "Special", 1.55), ("DLX War Machine Chrome", "Special", 1.5),
    ("FigZero Armored Titan Deluxe", "Special", 1.55), ("threezeroX Collaboration A", "Special", 1.5),
    ("threezeroX Collaboration B", "Special", 1.5), ("DLX Effect Pack", "Accessories", 1.3, 50),
    ("FigZero Stand Pack", "Accessories", 1.25, 35), ("DLX Bumblebee Chrome", "Special", 1.5),
    ("FigZero Naruto Deluxe", "Special", 1.55),
], 2018, 3, 2, 180)

add(data, "hottoys", "ht", [
    ("MMS Iron Man Mark 85", "MMS", 1.55), ("MMS Iron Man Mark 50", "MMS", 1.55),
    ("MMS Captain America Endgame", "MMS", 1.5), ("MMS Thor Endgame", "MMS", 1.5),
    ("MMS Spider-Man No Way Home", "MMS", 1.55), ("MMS Doctor Strange", "MMS", 1.5),
    ("MMS Batman The Batman", "MMS", 1.55), ("MMS Joker Folie", "MMS", 1.5),
    ("MMS Superman Black", "MMS", 1.5), ("MMS Wonder Woman", "MMS", 1.45),
    ("MMS Darth Vader", "MMS", 1.55), ("MMS Luke Skywalker", "MMS", 1.5),
    ("MMS Din Djarin", "MMS", 1.55), ("MMS Boba Fett", "MMS", 1.55),
    ("MMS Ahsoka", "MMS", 1.5), ("MMS Obi-Wan", "MMS", 1.5),
    ("MMS T-800", "MMS", 1.55), ("MMS RoboCop", "MMS", 1.5),
    ("MMS Alien", "MMS", 1.55), ("MMS Predator", "MMS", 1.55),
    ("MMS Iron Man Chrome", "Special", 1.55), ("MMS Cap Chrome", "Special", 1.5),
    ("MMS Batman Deluxe", "Special", 1.55), ("MMS Vader Deluxe", "Special", 1.55),
    ("MMS Spider-Man Integrated", "Special", 1.55), ("MMS Strange Multiverse", "Special", 1.55),
    ("MMS Mando Deluxe", "Special", 1.55), ("MMS Boba Deluxe", "Special", 1.55),
    ("MMS Thor Stormbreaker", "Special", 1.55), ("MMS Iron Man Mark 85 Battle", "Special", 1.55),
    ("MMS Joker Deluxe", "Special", 1.55), ("MMS Superman Deluxe", "Special", 1.5),
    ("MMS Luke Jedi", "Special", 1.55), ("MMS Ahsoka Deluxe", "Special", 1.55),
    ("MMS T-800 Battle Damaged", "Special", 1.55), ("MMS RoboCop Battle", "Special", 1.5),
    ("MMS Alien Warrior", "Special", 1.55), ("MMS Predator Jungle", "Special", 1.55),
    ("MMS War Machine", "MMS", 1.5), ("MMS Black Panther", "MMS", 1.5),
    ("MMS Scarlet Witch", "MMS", 1.5), ("MMS Loki", "MMS", 1.5),
    ("MMS Deadpool", "MMS", 1.55), ("MMS Wolverine", "MMS", 1.55),
    ("MMS Thanos", "MMS", 1.55),
], 2019, 1, 1, 350)

add(data, "beastkingdom", "bk", [
    ("DAH Iron Man", "DAH", 1.55), ("DAH Captain America", "DAH", 1.5),
    ("DAH Thor", "DAH", 1.5), ("DAH Hulk", "DAH", 1.5),
    ("DAH Spider-Man", "DAH", 1.55), ("DAH Black Panther", "DAH", 1.5),
    ("DAH Batman", "DAH", 1.55), ("DAH Superman", "DAH", 1.5),
    ("DAH Joker", "DAH", 1.55), ("DAH Wonder Woman", "DAH", 1.45),
    ("DAH Darth Vader", "DAH", 1.55), ("DAH Luke Skywalker", "DAH", 1.5),
    ("DAH Din Djarin", "DAH", 1.5), ("DAH Boba Fett", "DAH", 1.5),
    ("DAH Sonic", "DAH", 1.45), ("DAH Shadow", "DAH", 1.45),
    ("DAH Mario", "DAH", 1.4), ("DAH Luigi", "DAH", 1.35),
    ("DAH Iron Man Chrome", "Special", 1.55), ("DAH Batman Chrome", "Special", 1.55),
    ("DAH Spider-Man Symbiote", "Special", 1.55), ("DAH Joker Deluxe", "Special", 1.55),
    ("DAH Vader Deluxe", "Special", 1.55), ("DAH Mando Deluxe", "Special", 1.55),
    ("DAH Sonic Deluxe", "Special", 1.5), ("DAH Mario Deluxe", "Special", 1.45),
    ("DAH Thor Stormbreaker", "Special", 1.55), ("DAH Cap Endgame", "Special", 1.5),
    ("DAH Black Panther Chrome", "Special", 1.55), ("DAH Superman Black", "Special", 1.5),
    ("DAH Wonder Woman Deluxe", "Special", 1.5), ("DAH Hulk Smash", "Special", 1.5),
    ("DAH Boba Deluxe", "Special", 1.55), ("DAH Luke Jedi", "Special", 1.5),
    ("DAH Shadow Chrome", "Special", 1.5), ("DAH Luigi Deluxe", "Special", 1.4),
    ("DAH Accessories Pack", "Accessories", 1.25, 40), ("DAH Stand Pack", "Accessories", 1.2, 30),
    ("DAH Iron Man Mark 85", "DAH", 1.55), ("DAH Spider-Man No Way Home", "DAH", 1.55),
    ("DAH Batman The Batman", "DAH", 1.55), ("DAH Doctor Strange", "DAH", 1.5),
    ("DAH Scarlet Witch", "DAH", 1.5), ("DAH Loki", "DAH", 1.5),
    ("DAH Deadpool", "DAH", 1.55),
], 2018, 4, 2, 150)

add(data, "enterbay", "eb", [
    ("RM-1086 Kobe Bryant", "NBA", 1.55), ("RM-1090 Michael Jordan", "NBA", 1.55),
    ("RM-1095 LeBron James", "NBA", 1.55), ("RM-1100 Stephen Curry", "NBA", 1.5),
    ("RM-1105 Kevin Durant", "NBA", 1.5), ("RM-1110 Giannis", "NBA", 1.5),
    ("RM-1115 Luka Doncic", "NBA", 1.45), ("RM-1120 Ja Morant", "NBA", 1.45),
    ("HD-1001 Bruce Lee", "Movie", 1.55), ("HD-1005 Bruce Lee Yellow", "Movie", 1.55),
    ("HD-1010 Ip Man", "Movie", 1.5), ("HD-1015 Jet Li", "Movie", 1.5),
    ("HD-1020 Jackie Chan", "Movie", 1.5), ("HD-1025 Donnie Yen", "Movie", 1.5),
    ("HD-1030 Movie Hero A", "Movie", 1.45), ("HD-1035 Movie Hero B", "Movie", 1.45),
    ("NBA Kobe Deluxe", "Special", 1.55), ("NBA Jordan Deluxe", "Special", 1.55),
    ("NBA LeBron Deluxe", "Special", 1.55), ("NBA Curry Deluxe", "Special", 1.55),
    ("Bruce Lee Deluxe", "Special", 1.55), ("Bruce Lee Chrome", "Special", 1.55),
    ("Ip Man Deluxe", "Special", 1.55), ("Jet Li Deluxe", "Special", 1.5),
    ("Jackie Chan Deluxe", "Special", 1.55), ("Donnie Yen Deluxe", "Special", 1.55),
    ("NBA All-Star Pack", "Special", 1.5, 400), ("Martial Arts Pack", "Special", 1.5, 380),
    ("RM Alternate Jersey A", "NBA", 1.45), ("RM Alternate Jersey B", "NBA", 1.45),
    ("RM Alternate Jersey C", "NBA", 1.4), ("RM Alternate Jersey D", "NBA", 1.4),
    ("HD Movie Villain A", "Movie", 1.45), ("HD Movie Villain B", "Movie", 1.45),
    ("NBA Head Sculpt Pack", "Accessories", 1.3, 60), ("Movie Head Sculpt Pack", "Accessories", 1.3, 60),
    ("NBA Accessory Pack", "Accessories", 1.25, 45), ("Movie Weapon Pack", "Accessories", 1.25, 45),
    ("Kobe Finals", "Special", 1.55), ("Jordan Flu Game", "Special", 1.55),
    ("LeBron Finals", "Special", 1.55), ("Bruce Lee Enter the Dragon", "Special", 1.55),
    ("Ip Man Wing Chun", "Special", 1.55), ("Jackie Chan Drunken Master", "Special", 1.55),
    ("Enterbay Display Case", "Accessories", 1.2, 80),
], 2015, 2, 2, 280)

add(data, "fourhorsemen", "fh", [
    ("Mythic Legions Knight A", "Mythic Legions", 1.5), ("Mythic Legions Knight B", "Mythic Legions", 1.45),
    ("Mythic Legions Orc A", "Mythic Legions", 1.45), ("Mythic Legions Orc B", "Mythic Legions", 1.4),
    ("Mythic Legions Elf Archer", "Mythic Legions", 1.45), ("Mythic Legions Dwarf", "Mythic Legions", 1.4),
    ("Mythic Legions Skeleton", "Mythic Legions", 1.4), ("Mythic Legions Necromancer", "Mythic Legions", 1.5),
    ("Mythic Legions Barbarian", "Mythic Legions", 1.45), ("Mythic Legions Sorceress", "Mythic Legions", 1.45),
    ("Cosmic Legions Hero A", "Cosmic Legions", 1.5), ("Cosmic Legions Hero B", "Cosmic Legions", 1.45),
    ("Cosmic Legions Villain A", "Cosmic Legions", 1.5), ("Cosmic Legions Villain B", "Cosmic Legions", 1.45),
    ("Cosmic Legions Alien A", "Cosmic Legions", 1.4), ("Cosmic Legions Alien B", "Cosmic Legions", 1.4),
    ("Figura Obscura Headless Horseman", "Figura Obscura", 1.55), ("Figura Obscura Krampus", "Figura Obscura", 1.55),
    ("Figura Obscura Father Christmas", "Figura Obscura", 1.5), ("Figura Obscura Bloody Mary", "Figura Obscura", 1.5),
    ("Mythic Legions Deluxe Knight", "Special", 1.55), ("Mythic Legions Deluxe Orc", "Special", 1.5),
    ("Cosmic Legions Deluxe Hero", "Special", 1.55), ("Cosmic Legions Deluxe Villain", "Special", 1.55),
    ("Figura Obscura Deluxe Horseman", "Special", 1.55), ("Figura Obscura Deluxe Krampus", "Special", 1.55),
    ("Mythic Legions Horse", "Mythic Legions", 1.45), ("Mythic Legions Dragon", "Mythic Legions", 1.55),
    ("Cosmic Legions Steed", "Cosmic Legions", 1.4), ("Cosmic Legions Mech", "Cosmic Legions", 1.5),
    ("Mythic Legions Goblin", "Mythic Legions", 1.35), ("Mythic Legions Troll", "Mythic Legions", 1.45),
    ("Mythic Legions Angel", "Mythic Legions", 1.5), ("Mythic Legions Demon", "Mythic Legions", 1.5),
    ("Cosmic Legions Trooper", "Cosmic Legions", 1.35), ("Cosmic Legions Commander", "Cosmic Legions", 1.45),
    ("Figura Obscura Baba Yaga", "Figura Obscura", 1.5), ("Figura Obscura Frankenstein", "Figura Obscura", 1.5),
    ("Mythic Accessory Pack", "Accessories", 1.25, 30), ("Cosmic Accessory Pack", "Accessories", 1.25, 30),
    ("Figura Obscura Accessory", "Accessories", 1.3, 35), ("Mythic Legions Clear Knight", "Special", 1.45),
    ("Cosmic Legions Neon", "Special", 1.45), ("Figura Obscura Glow", "Special", 1.5),
    ("Four Horsemen Starter", "Special", 1.4, 100),
], 2018, 6, 2, 45)

add(data, "valaverse", "vv", [
    ("Action Force Trooper A", "Action Force", 1.4), ("Action Force Trooper B", "Action Force", 1.4),
    ("Action Force Trooper C", "Action Force", 1.35), ("Action Force Trooper D", "Action Force", 1.35),
    ("Action Force Officer", "Action Force", 1.45), ("Action Force Commander", "Action Force", 1.5),
    ("Action Force Sniper", "Action Force", 1.45), ("Action Force Medic", "Action Force", 1.35),
    ("Action Force Heavy", "Action Force", 1.4), ("Action Force Pilot", "Action Force", 1.4),
    ("Action Force Enemy A", "Action Force", 1.4), ("Action Force Enemy B", "Action Force", 1.4),
    ("Action Force Enemy C", "Action Force", 1.35), ("Action Force Enemy Boss", "Action Force", 1.5),
    ("Action Force Female Operative", "Action Force", 1.4), ("Action Force Female Sniper", "Action Force", 1.45),
    ("Action Force Desert", "Special", 1.4), ("Action Force Night Ops", "Special", 1.45),
    ("Action Force Winter", "Special", 1.4), ("Action Force Jungle", "Special", 1.4),
    ("Action Force Deluxe Trooper", "Special", 1.5), ("Action Force Deluxe Commander", "Special", 1.55),
    ("Action Force Deluxe Enemy", "Special", 1.5), ("Action Force Vehicle Driver", "Action Force", 1.4),
    ("Action Force Scientist", "Action Force", 1.35), ("Action Force Engineer", "Action Force", 1.35),
    ("Action Force Scout", "Action Force", 1.4), ("Action Force Breacher", "Action Force", 1.4),
    ("Weapon Pack AF A", "Accessories", 1.25, 20), ("Weapon Pack AF B", "Accessories", 1.25, 20),
    ("Head Pack AF", "Accessories", 1.25, 18), ("Gear Pack AF", "Accessories", 1.3, 25),
    ("Action Force Clear", "Special", 1.4), ("Action Force Chrome", "Special", 1.45),
    ("Action Force Glow", "Special", 1.4), ("Action Force Battle Damaged", "Special", 1.45),
    ("Action Force Female Deluxe", "Special", 1.5), ("Action Force Enemy Deluxe", "Special", 1.5),
    ("Action Force Starter Set", "Special", 1.4, 70), ("Action Force Squad Pack", "Special", 1.45, 90),
    ("Action Force Urban", "Special", 1.4), ("Action Force Arctic", "Special", 1.4),
    ("Action Force Spec Ops Pack", "Special", 1.5, 85), ("Action Force Enemy Pack", "Special", 1.45, 80),
    ("Valaverse Display Stand", "Accessories", 1.15, 12),
], 2019, 5, 1, 25)

add(data, "bossfight", "bf", [
    ("H.A.C.K.S. Warrior A", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Warrior B", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Skeleton", "H.A.C.K.S.", 1.45), ("H.A.C.K.S. Knight", "H.A.C.K.S.", 1.45),
    ("H.A.C.K.S. Orc", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Elf", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Goblin", "H.A.C.K.S.", 1.35), ("H.A.C.K.S. Demon", "H.A.C.K.S.", 1.45),
    ("H.A.C.K.S. Angel", "H.A.C.K.S.", 1.45), ("H.A.C.K.S. Vampire", "H.A.C.K.S.", 1.45),
    ("H.A.C.K.S. Werewolf", "H.A.C.K.S.", 1.45), ("H.A.C.K.S. Zombie", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Sci-Fi Trooper", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Sci-Fi Alien", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Robot", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Cyborg", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Female Warrior", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Female Mage", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Female Assassin", "H.A.C.K.S.", 1.45), ("H.A.C.K.S. Female Sci-Fi", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Deluxe Knight", "Special", 1.5), ("H.A.C.K.S. Deluxe Demon", "Special", 1.5),
    ("H.A.C.K.S. Deluxe Vampire", "Special", 1.5), ("H.A.C.K.S. Deluxe Sci-Fi", "Special", 1.45),
    ("Body Pack Male", "Accessories", 1.3, 15), ("Body Pack Female", "Accessories", 1.3, 15),
    ("Head Pack Fantasy", "Accessories", 1.25, 12), ("Head Pack Sci-Fi", "Accessories", 1.25, 12),
    ("Weapon Pack Fantasy", "Accessories", 1.25, 12), ("Weapon Pack Sci-Fi", "Accessories", 1.25, 12),
    ("H.A.C.K.S. Clear Skeleton", "Special", 1.45), ("H.A.C.K.S. Glow Demon", "Special", 1.45),
    ("H.A.C.K.S. Chrome Robot", "Special", 1.45), ("H.A.C.K.S. Neon Cyborg", "Special", 1.4),
    ("H.A.C.K.S. Starter Set", "Special", 1.35, 40), ("H.A.C.K.S. Army Builder", "Special", 1.4, 50),
    ("H.A.C.K.S. Dragon", "H.A.C.K.S.", 1.55), ("H.A.C.K.S. Horse", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Steed Sci-Fi", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Monster A", "H.A.C.K.S.", 1.4),
    ("H.A.C.K.S. Monster B", "H.A.C.K.S.", 1.4), ("H.A.C.K.S. Boss Figure", "Special", 1.5),
    ("Gear Pack A", "Accessories", 1.2, 10), ("Gear Pack B", "Accessories", 1.2, 10),
    ("Boss Fight Display", "Accessories", 1.15, 12),
], 2017, 1, 1, 20)

add(data, "loyalsubjects", "ls", [
    ("BST AXN Batman", "BST AXN", 1.5), ("BST AXN Superman", "BST AXN", 1.45),
    ("BST AXN Wonder Woman", "BST AXN", 1.45), ("BST AXN The Flash", "BST AXN", 1.4),
    ("BST AXN Joker", "BST AXN", 1.5), ("BST AXN Harley Quinn", "BST AXN", 1.5),
    ("BST AXN Spider-Man", "BST AXN", 1.5), ("BST AXN Venom", "BST AXN", 1.5),
    ("BST AXN Miles Morales", "BST AXN", 1.45), ("BST AXN Spider-Gwen", "BST AXN", 1.45),
    ("BST AXN TMNT Leonardo", "BST AXN", 1.5), ("BST AXN TMNT Michelangelo", "BST AXN", 1.45),
    ("BST AXN TMNT Donatello", "BST AXN", 1.45), ("BST AXN TMNT Raphael", "BST AXN", 1.5),
    ("BST AXN Shredder", "BST AXN", 1.5), ("BST AXN Splinter", "BST AXN", 1.4),
    ("BST AXN Naruto", "BST AXN", 1.5), ("BST AXN Sasuke", "BST AXN", 1.5),
    ("BST AXN Kakashi", "BST AXN", 1.45), ("BST AXN Itachi", "BST AXN", 1.5),
    ("BST AXN Batman Deluxe", "Special", 1.55), ("BST AXN Joker Deluxe", "Special", 1.55),
    ("BST AXN Spider-Man Deluxe", "Special", 1.55), ("BST AXN Venom Deluxe", "Special", 1.55),
    ("BST AXN Leonardo Deluxe", "Special", 1.55), ("BST AXN Raphael Deluxe", "Special", 1.55),
    ("BST AXN Naruto Deluxe", "Special", 1.55), ("BST AXN Sasuke Deluxe", "Special", 1.55),
    ("BST AXN Clear Batman", "Special", 1.45), ("BST AXN Glow Joker", "Special", 1.45),
    ("BST AXN Chrome Spider-Man", "Special", 1.5), ("BST AXN Neon Venom", "Special", 1.5),
    ("BST AXN Casey Jones", "BST AXN", 1.4), ("BST AXN April O'Neil", "BST AXN", 1.35),
    ("BST AXN Bebop", "BST AXN", 1.4), ("BST AXN Rocksteady", "BST AXN", 1.4),
    ("BST AXN Green Goblin", "BST AXN", 1.45), ("BST AXN Doctor Octopus", "BST AXN", 1.45),
    ("BST AXN Deathstroke", "BST AXN", 1.45), ("BST AXN Nightwing", "BST AXN", 1.4),
    ("BST AXN Accessory Pack", "Accessories", 1.25, 15), ("BST AXN Stand Pack", "Accessories", 1.2, 12),
    ("BST AXN TMNT Pack", "Special", 1.5, 80), ("BST AXN Marvel Pack", "Special", 1.5, 75),
    ("BST AXN DC Pack", "Special", 1.5, 75),
], 2020, 3, 1, 20)

add(data, "jada", "jd", [
    ("Street Fighter Ryu", "Street Fighter", 1.5), ("Street Fighter Ken", "Street Fighter", 1.5),
    ("Street Fighter Chun-Li", "Street Fighter", 1.55), ("Street Fighter Guile", "Street Fighter", 1.45),
    ("Street Fighter Akuma", "Street Fighter", 1.55), ("Street Fighter M. Bison", "Street Fighter", 1.5),
    ("Street Fighter Cammy", "Street Fighter", 1.5), ("Street Fighter Dhalsim", "Street Fighter", 1.4),
    ("Universal Dracula", "Universal Monsters", 1.45), ("Universal Frankenstein", "Universal Monsters", 1.45),
    ("Universal Wolfman", "Universal Monsters", 1.4), ("Universal Mummy", "Universal Monsters", 1.4),
    ("Universal Creature", "Universal Monsters", 1.45), ("Universal Bride", "Universal Monsters", 1.45),
    ("DC Batman", "DC", 1.5), ("DC Superman", "DC", 1.45),
    ("DC Wonder Woman", "DC", 1.45), ("DC The Flash", "DC", 1.4),
    ("DC Joker", "DC", 1.5), ("DC Harley Quinn", "DC", 1.5),
    ("Marvel Spider-Man", "Marvel", 1.5), ("Marvel Iron Man", "Marvel", 1.5),
    ("Marvel Captain America", "Marvel", 1.45), ("Marvel Thor", "Marvel", 1.45),
    ("Marvel Hulk", "Marvel", 1.45), ("Marvel Black Panther", "Marvel", 1.45),
    ("SF Ryu Deluxe", "Special", 1.55), ("SF Chun-Li Deluxe", "Special", 1.55),
    ("SF Akuma Deluxe", "Special", 1.55), ("Universal Dracula Deluxe", "Special", 1.5),
    ("DC Batman Deluxe", "Special", 1.55), ("Marvel Spider-Man Deluxe", "Special", 1.55),
    ("SF Guile Deluxe", "Special", 1.45), ("SF Dhalsim Deluxe", "Special", 1.4),
    ("SF Cammy Deluxe", "Special", 1.5), ("SF Bison Deluxe", "Special", 1.5),
    ("Universal Frankenstein Deluxe", "Special", 1.5), ("DC Joker Deluxe", "Special", 1.55),
    ("Marvel Iron Man Deluxe", "Special", 1.55), ("Marvel Cap Deluxe", "Special", 1.5),
    ("Jada SF 2-Pack", "Special", 1.5, 50), ("Jada Universal 2-Pack", "Special", 1.45, 45),
    ("Jada DC 2-Pack", "Special", 1.5, 45), ("Jada Marvel 2-Pack", "Special", 1.5, 45),
    ("Jada Display Stand", "Accessories", 1.15, 10),
], 2019, 4, 1, 25)

add(data, "bandai", "bn", [
    ("Robot Spirits Gundam RX-78", "Robot Spirits", 1.55), ("Robot Spirits Zaku II", "Robot Spirits", 1.5),
    ("Robot Spirits Char Zaku", "Robot Spirits", 1.55), ("Robot Spirits Wing Zero", "Robot Spirits", 1.55),
    ("Robot Spirits Freedom", "Robot Spirits", 1.5), ("Robot Spirits Destiny", "Robot Spirits", 1.5),
    ("Robot Spirits Unicorn", "Robot Spirits", 1.55), ("Robot Spirits Barbatos", "Robot Spirits", 1.55),
    ("Gundam Universe RX-78", "Gundam Universe", 1.45), ("Gundam Universe Zaku", "Gundam Universe", 1.4),
    ("Gundam Universe Wing", "Gundam Universe", 1.45), ("Gundam Universe Unicorn", "Gundam Universe", 1.5),
    ("G Frame RX-78", "G Frame", 1.4), ("G Frame Zaku", "G Frame", 1.35),
    ("G Frame Wing", "G Frame", 1.4), ("G Frame Unicorn", "G Frame", 1.45),
    ("MSiA Gundam", "MSiA", 1.4), ("MSiA Char Zaku", "MSiA", 1.45),
    ("MSiA Wing Zero", "MSiA", 1.45), ("MSiA Freedom", "MSiA", 1.4),
    ("Robot Spirits Chrome", "Special", 1.55), ("Robot Spirits Clear", "Special", 1.5),
    ("Gundam Universe Chrome", "Special", 1.5), ("G Frame Metallic", "Special", 1.45),
    ("Robot Spirits Eva-01 Homage", "Special", 1.5), ("Robot Spirits Mazinger Homage", "Special", 1.5),
    ("Gundam Universe Barbatos", "Gundam Universe", 1.5), ("Gundam Universe Destiny", "Gundam Universe", 1.45),
    ("Robot Spirits Nu Gundam", "Robot Spirits", 1.55), ("Robot Spirits Sazabi", "Robot Spirits", 1.55),
    ("Robot Spirits Hi-Nu", "Robot Spirits", 1.55), ("Robot Spirits Nightingale", "Robot Spirits", 1.5),
    ("G Frame Effect Parts", "Accessories", 1.25, 20), ("Robot Spirits Stand", "Accessories", 1.2, 25),
    ("MSiA Chrome", "Special", 1.45), ("Gundam Universe Clear", "Special", 1.4),
    ("Robot Spirits Battle Damaged", "Special", 1.5), ("G Frame Combo Pack", "Special", 1.4, 60),
    ("Robot Spirits Weapon Pack", "Accessories", 1.3, 35), ("Gundam Universe Pack", "Special", 1.4, 70),
    ("Robot Spirits Exia", "Robot Spirits", 1.5), ("Robot Spirits 00 Raiser", "Robot Spirits", 1.55),
    ("Gundam Universe Exia", "Gundam Universe", 1.45), ("G Frame Exia", "G Frame", 1.4),
    ("Bandai AF Starter", "Special", 1.35, 55),
], 2016, 2, 1, 75)

add(data, "playmates", "pm", [
    ("Classic Leonardo", "TMNT Classic", 1.5), ("Classic Michelangelo", "TMNT Classic", 1.45),
    ("Classic Donatello", "TMNT Classic", 1.45), ("Classic Raphael", "TMNT Classic", 1.5),
    ("Classic Splinter", "TMNT Classic", 1.45), ("Classic Shredder", "TMNT Classic", 1.55),
    ("Classic Casey Jones", "TMNT Classic", 1.4), ("Classic April O'Neil", "TMNT Classic", 1.35),
    ("Classic Bebop", "TMNT Classic", 1.4), ("Classic Rocksteady", "TMNT Classic", 1.4),
    ("Classic Krang", "TMNT Classic", 1.5), ("Classic Foot Soldier", "TMNT Classic", 1.3),
    ("Mutant Mayhem Leo", "Mutant Mayhem", 1.5), ("Mutant Mayhem Mikey", "Mutant Mayhem", 1.45),
    ("Mutant Mayhem Donnie", "Mutant Mayhem", 1.45), ("Mutant Mayhem Raph", "Mutant Mayhem", 1.5),
    ("Mutant Mayhem Splinter", "Mutant Mayhem", 1.4), ("Mutant Mayhem Superfly", "Mutant Mayhem", 1.45),
    ("Tales of TMNT Leo", "Tales", 1.45), ("Tales of TMNT Raph", "Tales", 1.45),
    ("Classic Collection Leo", "Classic Collection", 1.5), ("Classic Collection Raph", "Classic Collection", 1.5),
    ("Classic Collection Mikey", "Classic Collection", 1.45), ("Classic Collection Donnie", "Classic Collection", 1.45),
    ("Exo-Squad Able Squad", "Exo-Squad", 1.4), ("Exo-Squad Neosapien", "Exo-Squad", 1.4),
    ("Classic Leo Soft Goods", "Special", 1.55), ("Classic Shredder Soft Goods", "Special", 1.55),
    ("Mutant Mayhem Deluxe Leo", "Special", 1.55), ("Mutant Mayhem Deluxe Raph", "Special", 1.55),
    ("Classic Krang Soft Goods", "Special", 1.5), ("Classic Bebop Soft Goods", "Special", 1.45),
    ("Classic Rocksteady Soft Goods", "Special", 1.45), ("Classic Foot Soft Goods", "Special", 1.35),
    ("Tales Deluxe Leo", "Special", 1.5), ("Tales Deluxe Raph", "Special", 1.5),
    ("Classic Collection Soft Leo", "Special", 1.55), ("Classic Collection Soft Raph", "Special", 1.55),
    ("Exo-Squad Deluxe", "Special", 1.45), ("TMNT Vehicle Driver", "TMNT Classic", 1.35),
    ("Classic Accessory Pack", "Accessories", 1.25, 15), ("Mutant Mayhem Accessory", "Accessories", 1.25, 15),
    ("Classic 4-Pack", "Special", 1.5, 60), ("Mutant Mayhem 4-Pack", "Special", 1.5, 55),
    ("Playmates Display", "Accessories", 1.15, 12),
], 1988, 6, 3, 8)

add(data, "mattel", "mt", [
    ("Masterverse He-Man", "Masterverse", 1.55), ("Masterverse Skeletor", "Masterverse", 1.55),
    ("Masterverse Teela", "Masterverse", 1.45), ("Masterverse Man-At-Arms", "Masterverse", 1.45),
    ("Masterverse Evil-Lyn", "Masterverse", 1.5), ("Masterverse Beast Man", "Masterverse", 1.45),
    ("Masterverse Stratos", "Masterverse", 1.4), ("Masterverse Mer-Man", "Masterverse", 1.4),
    ("Masterverse Trap Jaw", "Masterverse", 1.45), ("Masterverse Tri-Klops", "Masterverse", 1.4),
    ("Masterverse Hordak", "Masterverse", 1.5), ("Masterverse She-Ra", "Masterverse", 1.5),
    ("WWE Elite John Cena", "WWE Elite", 1.45), ("WWE Elite Roman Reigns", "WWE Elite", 1.5),
    ("WWE Elite Rhea Ripley", "WWE Elite", 1.5), ("WWE Elite Cody Rhodes", "WWE Elite", 1.5),
    ("WWE Ultimate Undertaker", "WWE Ultimate", 1.55), ("WWE Ultimate Stone Cold", "WWE Ultimate", 1.55),
    ("WWE Ultimate Shawn Michaels", "WWE Ultimate", 1.5), ("WWE Ultimate Triple H", "WWE Ultimate", 1.5),
    ("Origins He-Man", "Origins", 1.45), ("Origins Skeletor", "Origins", 1.45),
    ("Origins Teela", "Origins", 1.4), ("Origins Man-At-Arms", "Origins", 1.4),
    ("Masterverse New Eternia He-Man", "Masterverse", 1.55), ("Masterverse New Eternia Skeletor", "Masterverse", 1.55),
    ("Masterverse Revolution He-Man", "Masterverse", 1.5), ("Masterverse Revolution Skeletor", "Masterverse", 1.5),
    ("Masterverse Deluxe He-Man", "Special", 1.55), ("Masterverse Deluxe Skeletor", "Special", 1.55),
    ("WWE Elite Deluxe Cena", "Special", 1.5), ("WWE Ultimate Deluxe Undertaker", "Special", 1.55),
    ("Origins Deluxe He-Man", "Special", 1.5), ("Origins Deluxe Skeletor", "Special", 1.5),
    ("Masterverse Battle Cat", "Masterverse", 1.5), ("Masterverse Panthor", "Masterverse", 1.5),
    ("Masterverse Catra", "Masterverse", 1.5), ("Masterverse Orko", "Masterverse", 1.4),
    ("WWE Elite Becky Lynch", "WWE Elite", 1.45), ("WWE Elite Seth Rollins", "WWE Elite", 1.45),
    ("WWE Ultimate Randy Savage", "WWE Ultimate", 1.55), ("WWE Ultimate Ultimate Warrior", "WWE Ultimate", 1.55),
    ("Masterverse Creations Exclusive", "Special", 1.55), ("Origins Cartoon Collection", "Special", 1.45),
    ("Mattel AF Accessory Pack", "Accessories", 1.2, 12),
], 2020, 1, 1, 22.99)

OUT.write_text(json.dumps(data, indent=2) + "\n")
counts = {k: len(v) for k, v in data.items()}
print(json.dumps(counts, indent=2))
print("TOTAL", sum(counts.values()))
NEW = ["mego","worldbox","kaustic","poptoys","deviltoys","kingarts","jtstudio","artspirits","artstorm","fiftytwo","actiontoys","underverse"]
DEN = ["neca","super7","threezero","hottoys","beastkingdom","enterbay","fourhorsemen","valaverse","bossfight","loyalsubjects","jada","bandai","playmates","mattel"]
print("NEW", sum(counts[k] for k in NEW))
print("DENSIFY", sum(counts[k] for k in DEN))
