#!/usr/bin/env python3
"""Generate bbts_wave10_data.json — BBTS AF brand expansion wave 10 (FINAL)."""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).with_name("bbts_wave10_data.json")

def R(suf, name, sub, date, demand, msrp=None):
    row = [suf, name, sub, date, float(demand)]
    if msrp is not None:
        row.append(float(msrp))
    return row

def dates(y, m, n, step=1):
    out = []
    for _ in range(n):
        out.append(f"{y:04d}-{m:02d}-01")
        m += step
        while m > 12:
            m -= 12
            y += 1
    return out

def add(data, key, prefix, items, y, m, step, default_msrp):
    ds = dates(y, m, len(items), step)
    rows = []
    for i, it in enumerate(items):
        if len(it) == 4:
            name, sub, demand, msrp = it
        else:
            name, sub, demand = it
            msrp = default_msrp
        rows.append(R(f"{prefix}-{i+1:02d}", name, sub, max(ds[i], "1980-01-01"), demand, msrp))
    data[key] = rows

def pad45(items, filler_sub="Special", demand=1.4):
    """Ensure exactly 45 items by adding numbered deluxe/specials."""
    out = list(items)
    i = 1
    while len(out) < 45:
        out.append((f"{filler_sub} Exclusive {i:02d}", filler_sub, min(1.55, demand + 0.05)))
        i += 1
    return out[:45]

data: dict[str, list] = {}

# ========== NEW (12) ==========
add(data, "haoyu", "hy", pad45([
    ("German WWII Infantry", "WWII", 1.45), ("German WWII Officer", "WWII", 1.5),
    ("German WWII Sniper", "WWII", 1.45), ("German WWII Panzer Crew", "WWII", 1.4),
    ("US WWII Infantry", "WWII", 1.5), ("US WWII Paratrooper", "WWII", 1.55),
    ("US WWII Marine", "WWII", 1.5), ("US WWII Medic", "WWII", 1.4),
    ("British WWII Commando", "WWII", 1.5), ("British WWII RAF", "WWII", 1.4),
    ("Soviet WWII Infantry", "WWII", 1.45), ("Soviet WWII Sniper", "WWII", 1.45),
    ("Modern SEAL", "Modern", 1.55), ("Modern Delta", "Modern", 1.55),
    ("Modern SAS", "Modern", 1.5), ("Modern Spetsnaz", "Modern", 1.5),
    ("PLA Modern Soldier", "Modern", 1.4), ("PMC Contractor", "Modern", 1.45),
    ("Vietnam US Infantry", "Vietnam", 1.5), ("Vietnam US MACV-SOG", "Vietnam", 1.55),
    ("Vietnam NVA", "Vietnam", 1.4), ("Vietnam Tunnel Rat", "Vietnam", 1.45),
    ("Chinese Ancient Warrior", "Historical", 1.5), ("Chinese Ming General", "Historical", 1.55),
    ("Samurai Warrior", "Historical", 1.55), ("Ninja Assassin", "Historical", 1.5),
    ("WWII German Deluxe", "Special", 1.55), ("WWII US Deluxe", "Special", 1.55),
    ("Modern SEAL Deluxe", "Special", 1.55), ("Vietnam SOG Deluxe", "Special", 1.55),
    ("Chinese Warrior Deluxe", "Special", 1.55), ("Samurai Deluxe", "Special", 1.55),
    ("Weapon Pack WWII", "Accessories", 1.3, 45), ("Weapon Pack Modern", "Accessories", 1.3, 45),
    ("Head Pack Military", "Accessories", 1.25, 35), ("Uniform Pack WWII", "Accessories", 1.35, 60),
    ("WWII British Deluxe", "Special", 1.5), ("WWII Soviet Deluxe", "Special", 1.45),
    ("Modern SAS Deluxe", "Special", 1.55), ("PMC Deluxe", "Special", 1.5),
    ("Vietnam US Deluxe", "Special", 1.5), ("Ninja Deluxe", "Special", 1.5),
    ("HaoYu Starter Set", "Special", 1.4, 280), ("Display Stand Military", "Accessories", 1.2, 25),
    ("WWII Panzer Deluxe", "Special", 1.45),
]), 2014, 3, 2, 189)

add(data, "bigchief", "bc", pad45([
    ("Fourth Doctor", "Doctor Who", 1.55), ("Tenth Doctor", "Doctor Who", 1.55),
    ("Eleventh Doctor", "Doctor Who", 1.5), ("Twelfth Doctor", "Doctor Who", 1.5),
    ("Thirteenth Doctor", "Doctor Who", 1.45), ("War Doctor", "Doctor Who", 1.5),
    ("Dalek Classic", "Doctor Who", 1.55), ("Dalek New Series", "Doctor Who", 1.5),
    ("Cyberman Classic", "Doctor Who", 1.5), ("Cyberman Mondasian", "Doctor Who", 1.45),
    ("Weeping Angel", "Doctor Who", 1.55), ("Silence", "Doctor Who", 1.45),
    ("Master Classic", "Doctor Who", 1.5), ("Missy", "Doctor Who", 1.5),
    ("Companion Rose", "Doctor Who", 1.4), ("Companion Clara", "Doctor Who", 1.4),
    ("Companion Donna", "Doctor Who", 1.35), ("Companion Amy", "Doctor Who", 1.4),
    ("James Bond Connery", "Film", 1.55), ("James Bond Moore", "Film", 1.45),
    ("James Bond Craig", "Film", 1.55), ("Bond Villain Blofeld", "Film", 1.5),
    ("Fourth Doctor Deluxe", "Special", 1.55), ("Tenth Doctor Deluxe", "Special", 1.55),
    ("Dalek Deluxe", "Special", 1.55), ("Cyberman Deluxe", "Special", 1.55),
    ("Weeping Angel Deluxe", "Special", 1.55), ("Bond Craig Deluxe", "Special", 1.55),
    ("TARDIS Accessory", "Accessories", 1.4, 80), ("Sonic Screwdriver Pack", "Accessories", 1.3, 40),
    ("Head Pack Doctors", "Accessories", 1.35, 55), ("Outfit Pack Classic", "Accessories", 1.35, 70),
    ("Eleventh Doctor Deluxe", "Special", 1.5), ("Twelfth Doctor Deluxe", "Special", 1.5),
    ("Master Deluxe", "Special", 1.55), ("Missy Deluxe", "Special", 1.5),
    ("Bond Connery Deluxe", "Special", 1.55), ("Dalek Chrome", "Special", 1.55),
    ("Cyberman Chrome", "Special", 1.5), ("War Doctor Deluxe", "Special", 1.55),
    ("BIG Chief Starter", "Special", 1.4, 300), ("Display Stand Who", "Accessories", 1.2, 30),
    ("Thirteenth Doctor Deluxe", "Special", 1.5),
]), 2015, 6, 2, 250)

add(data, "iconiq", "iq", pad45([
    ("IQ001 Street Fighter Ryu", "Street Fighter", 1.55), ("IQ002 Street Fighter Ken", "Street Fighter", 1.5),
    ("IQ003 Street Fighter Chun-Li", "Street Fighter", 1.55), ("IQ004 Street Fighter Guile", "Street Fighter", 1.45),
    ("IQ005 Street Fighter Akuma", "Street Fighter", 1.55), ("IQ006 Street Fighter M. Bison", "Street Fighter", 1.5),
    ("IQ007 Mortal Kombat Scorpion", "Mortal Kombat", 1.55), ("IQ008 Mortal Kombat Sub-Zero", "Mortal Kombat", 1.55),
    ("IQ009 Mortal Kombat Raiden", "Mortal Kombat", 1.5), ("IQ010 Mortal Kombat Liu Kang", "Mortal Kombat", 1.5),
    ("IQ011 Anime Hero A", "Anime", 1.5), ("IQ012 Anime Hero B", "Anime", 1.45),
    ("IQ013 Anime Heroine A", "Anime", 1.5), ("IQ014 Anime Heroine B", "Anime", 1.45),
    ("IQ015 Movie Icon A", "Movie", 1.5), ("IQ016 Movie Icon B", "Movie", 1.45),
    ("IQ017 Movie Icon C", "Movie", 1.45), ("IQ018 Movie Icon D", "Movie", 1.4),
    ("IQ019 Horror Icon A", "Horror", 1.5), ("IQ020 Horror Icon B", "Horror", 1.5),
    ("IQ001 Deluxe", "Special", 1.55), ("IQ003 Deluxe", "Special", 1.55),
    ("IQ005 Deluxe", "Special", 1.55), ("IQ007 Deluxe", "Special", 1.55),
    ("IQ008 Deluxe", "Special", 1.55), ("IQ011 Deluxe", "Special", 1.55),
    ("Weapon Pack SF", "Accessories", 1.3, 45), ("Weapon Pack MK", "Accessories", 1.3, 45),
    ("Head Pack Fighters", "Accessories", 1.35, 55), ("Effect Pack Hadoken", "Accessories", 1.35, 50),
    ("IQ Ryu Chrome", "Special", 1.55), ("IQ Chun-Li Chrome", "Special", 1.55),
    ("IQ Scorpion Glow", "Special", 1.55), ("IQ Sub-Zero Ice", "Special", 1.55),
    ("IQ Akuma Demon", "Special", 1.55), ("IQ Anime Hero Chrome", "Special", 1.5),
    ("IQ Movie Icon Deluxe", "Special", 1.5), ("IQ Horror Glow", "Special", 1.5),
    ("IQ019 Deluxe", "Special", 1.55), ("IQ020 Deluxe", "Special", 1.55),
    ("Iconiq Starter Set", "Special", 1.4, 320), ("Display Stand Iconiq", "Accessories", 1.2, 30),
    ("IQ Guile Deluxe", "Special", 1.5),
]), 2018, 4, 2, 260)

add(data, "figurestoy", "ftc", pad45([
    ("Superman Classic", "WGSH Style", 1.5), ("Batman Classic", "WGSH Style", 1.5),
    ("Robin Classic", "WGSH Style", 1.4), ("Wonder Woman Classic", "WGSH Style", 1.45),
    ("Aquaman Classic", "WGSH Style", 1.35), ("Flash Classic", "WGSH Style", 1.4),
    ("Green Lantern Classic", "WGSH Style", 1.4), ("Joker Classic", "WGSH Style", 1.5),
    ("Penguin Classic", "WGSH Style", 1.4), ("Riddler Classic", "WGSH Style", 1.4),
    ("Catwoman Classic", "WGSH Style", 1.45), ("Lex Luthor Classic", "WGSH Style", 1.4),
    ("Spider-Man Classic", "Marvel Style", 1.5), ("Hulk Classic", "Marvel Style", 1.45),
    ("Captain America Classic", "Marvel Style", 1.45), ("Iron Man Classic", "Marvel Style", 1.45),
    ("Thor Classic", "Marvel Style", 1.4), ("Wolverine Classic", "Marvel Style", 1.5),
    ("Green Hornet", "TV Heroes", 1.45), ("Kato", "TV Heroes", 1.45),
    ("Lone Ranger", "TV Heroes", 1.4), ("Tonto", "TV Heroes", 1.35),
    ("Superman Chase", "Special", 1.55), ("Batman Chase", "Special", 1.55),
    ("Spider-Man Chase", "Special", 1.55), ("Joker Chase", "Special", 1.55),
    ("2-Pack Heroes", "Special", 1.45, 40), ("2-Pack Villains", "Special", 1.45, 40),
    ("Retro Box Superman", "Special", 1.5), ("Retro Box Batman", "Special", 1.5),
    ("Retro Box Spider-Man", "Special", 1.5), ("Retro Box Joker", "Special", 1.5),
    ("Body Male Classic", "Bodies", 1.25, 18), ("Body Female Classic", "Bodies", 1.25, 18),
    ("Cape Pack", "Accessories", 1.2, 12), ("Weapon Pack Retro", "Accessories", 1.2, 15),
    ("Wonder Woman Chase", "Special", 1.5), ("Wolverine Chase", "Special", 1.55),
    ("Green Hornet Deluxe", "Special", 1.5), ("Lone Ranger Deluxe", "Special", 1.45),
    ("FTC Starter Set", "Special", 1.35, 70), ("Display Stand Retro", "Accessories", 1.15, 12),
    ("Batman 66 Style", "TV Heroes", 1.55),
]), 2012, 1, 2, 19.99)

add(data, "toynotch", "tn", pad45([
    ("TN001 Ming Warrior", "Chinese History", 1.5), ("TN002 Qing Bannerman", "Chinese History", 1.45),
    ("TN003 Tang Guard", "Chinese History", 1.45), ("TN004 Song Archer", "Chinese History", 1.4),
    ("TN005 Han General", "Chinese History", 1.55), ("TN006 Warring States", "Chinese History", 1.5),
    ("TN007 Shaolin Monk", "Martial", 1.5), ("TN008 Wudang Disciple", "Martial", 1.45),
    ("TN009 Mongol Rider", "Steppe", 1.5), ("TN010 Mongol Archer", "Steppe", 1.45),
    ("TN011 Tibetan Warrior", "Himalaya", 1.4), ("TN012 Himalayan Guard", "Himalaya", 1.35),
    ("TN013 Pirate Captain Asia", "Pirate", 1.45), ("TN014 Pirate Crew Asia", "Pirate", 1.35),
    ("TN015 Joseon Soldier", "Korea", 1.4), ("TN016 Joseon Archer", "Korea", 1.4),
    ("TN017 Samurai Ronin", "Japan", 1.55), ("TN018 Ashigaru", "Japan", 1.4),
    ("TN019 Ninja Iga", "Japan", 1.5), ("TN020 Onna-bugeisha", "Japan", 1.5),
    ("TN001 Deluxe", "Special", 1.55), ("TN005 Deluxe", "Special", 1.55),
    ("TN007 Deluxe", "Special", 1.55), ("TN017 Deluxe", "Special", 1.55),
    ("Weapon Pack Chinese", "Accessories", 1.3, 50), ("Weapon Pack Japan", "Accessories", 1.3, 50),
    ("Armor Pack Ming", "Accessories", 1.4, 80), ("Head Pack Historical", "Accessories", 1.3, 40),
    ("TN Ming Chrome", "Special", 1.5), ("TN Samurai Chrome", "Special", 1.55),
    ("TN Ninja Ghost", "Special", 1.5), ("TN Shaolin Deluxe", "Special", 1.55),
    ("TN Mongol Deluxe", "Special", 1.5), ("TN Pirate Deluxe", "Special", 1.45),
    ("TN Joseon Deluxe", "Special", 1.45), ("TN Warring Deluxe", "Special", 1.5),
    ("Toy Notch Starter", "Special", 1.4, 280), ("Display Stand Notch", "Accessories", 1.2, 28),
    ("TN Onna Deluxe", "Special", 1.55), ("TN Ashigaru Deluxe", "Special", 1.4),
    ("TN Qing Deluxe", "Special", 1.45),
]), 2016, 5, 2, 210)

add(data, "actoys", "ac", pad45([
    ("AC001 PLA Infantry", "PLA", 1.4), ("AC002 PLA Special Forces", "PLA", 1.5),
    ("AC003 PLA Sniper", "PLA", 1.45), ("AC004 PLA Officer", "PLA", 1.4),
    ("AC005 Russian Spetsnaz", "Russian", 1.5), ("AC006 Russian Infantry", "Russian", 1.4),
    ("AC007 Russian Sniper", "Russian", 1.45), ("AC008 Russian Officer", "Russian", 1.4),
    ("AC009 US Ranger", "US", 1.5), ("AC010 US Marine", "US", 1.5),
    ("AC011 US SEAL", "US", 1.55), ("AC012 US Delta", "US", 1.55),
    ("AC013 PMC Operator", "PMC", 1.45), ("AC014 PMC Sniper", "PMC", 1.45),
    ("AC015 Police SWAT", "Police", 1.4), ("AC016 Police HRT", "Police", 1.4),
    ("AC017 Sci-Fi Trooper", "Sci-Fi", 1.45), ("AC018 Sci-Fi Commander", "Sci-Fi", 1.45),
    ("AC019 Desert Operator", "Modern", 1.45), ("AC020 Jungle Operator", "Modern", 1.45),
    ("AC011 Deluxe", "Special", 1.55), ("AC012 Deluxe", "Special", 1.55),
    ("AC005 Deluxe", "Special", 1.55), ("AC002 Deluxe", "Special", 1.5),
    ("Weapon Pack Modern AC", "Accessories", 1.3, 42), ("Gear Pack Tactical", "Accessories", 1.35, 55),
    ("Head Pack Operators", "Accessories", 1.25, 32), ("Vest Pack Modular", "Accessories", 1.3, 48),
    ("AC SEAL Night", "Special", 1.55), ("AC Delta Desert", "Special", 1.55),
    ("AC Spetsnaz Winter", "Special", 1.5), ("AC PLA Urban", "Special", 1.45),
    ("AC PMC Chrome", "Special", 1.45), ("AC SWAT Deluxe", "Special", 1.45),
    ("AC Sci-Fi Neon", "Special", 1.45), ("AC Ranger Jungle", "Special", 1.5),
    ("ACToys Starter", "Special", 1.35, 260), ("Display Stand AC", "Accessories", 1.2, 25),
    ("AC Marine Deluxe", "Special", 1.5), ("AC Sniper Deluxe", "Special", 1.5),
    ("AC Desert Deluxe", "Special", 1.45),
]), 2017, 2, 2, 185)

add(data, "newwave", "nw", pad45([
    ("Replicade Dig Dug", "Replicade", 1.4, 40), ("Replicade Pac-Man", "Replicade", 1.45, 40),
    ("Replicade Galaga", "Replicade", 1.4, 40), ("Replicade Space Invaders", "Replicade", 1.45, 40),
    ("Wave 1 Ryu", "Street Fighter Wave", 1.5), ("Wave 1 Ken", "Street Fighter Wave", 1.45),
    ("Wave 1 Chun-Li", "Street Fighter Wave", 1.5), ("Wave 1 Guile", "Street Fighter Wave", 1.4),
    ("Wave 1 Blanka", "Street Fighter Wave", 1.4), ("Wave 1 Dhalsim", "Street Fighter Wave", 1.35),
    ("Wave 1 Zangief", "Street Fighter Wave", 1.4), ("Wave 1 M. Bison", "Street Fighter Wave", 1.5),
    ("Arcade Frogger", "Arcade Heroes", 1.35), ("Arcade Donkey Kong", "Arcade Heroes", 1.45),
    ("Arcade Mario Classic", "Arcade Heroes", 1.5), ("Arcade Link Classic", "Arcade Heroes", 1.45),
    ("Arcade Mega Man", "Arcade Heroes", 1.5), ("Arcade Sonic Classic", "Arcade Heroes", 1.5),
    ("Arcade Tortoise Hero", "Arcade Heroes", 1.4), ("Arcade Robot Master", "Arcade Heroes", 1.4),
    ("Wave 1 Ryu Chase", "Special", 1.55), ("Wave 1 Chun-Li Chase", "Special", 1.55),
    ("Wave 1 Bison Chase", "Special", 1.55), ("Arcade Mega Man Chase", "Special", 1.55),
    ("Replicade Clear Pac-Man", "Special", 1.45, 45), ("Replicade Glow Galaga", "Special", 1.4, 45),
    ("2-Pack Fighters", "Special", 1.45, 45), ("2-Pack Arcade", "Special", 1.4, 42),
    ("Wave Accessory Stick", "Accessories", 1.2, 12), ("Arcade Stand Pack", "Accessories", 1.15, 10),
    ("Wave 1 Akuma", "Street Fighter Wave", 1.55), ("Wave 1 Vega", "Street Fighter Wave", 1.4),
    ("Wave 1 Sagat", "Street Fighter Wave", 1.45), ("Wave 1 Balrog", "Street Fighter Wave", 1.35),
    ("Arcade Contra Hero", "Arcade Heroes", 1.4), ("Arcade Castlevania Hero", "Arcade Heroes", 1.45),
    ("Arcade Metal Slug", "Arcade Heroes", 1.4), ("Arcade Double Dragon", "Arcade Heroes", 1.4),
    ("New Wave Starter", "Special", 1.35, 55), ("Replicade Starter", "Special", 1.35, 50),
    ("Wave Clear Ryu", "Special", 1.5), ("Wave Glow Chun-Li", "Special", 1.5),
    ("Arcade Sonic Chase", "Special", 1.55),
]), 2019, 1, 1, 22.99)

add(data, "flirtygirl", "fg", pad45([
    ("FG001 Operative Luna", "Modern", 1.5), ("FG002 Operative Raven", "Modern", 1.5),
    ("FG003 Operative Viper", "Modern", 1.45), ("FG004 Operative Shadow", "Modern", 1.45),
    ("FG005 Assassin Crimson", "Assassin", 1.55), ("FG006 Assassin Night", "Assassin", 1.5),
    ("FG007 Assassin Silk", "Assassin", 1.5), ("FG008 Assassin Jade", "Assassin", 1.45),
    ("FG009 Fantasy Elf Archer", "Fantasy", 1.5), ("FG010 Fantasy Mage", "Fantasy", 1.45),
    ("FG011 Fantasy Knight", "Fantasy", 1.5), ("FG012 Fantasy Rogue", "Fantasy", 1.45),
    ("FG013 Sci-Fi Trooper", "Sci-Fi", 1.45), ("FG014 Sci-Fi Pilot", "Sci-Fi", 1.45),
    ("FG015 Sci-Fi Android", "Sci-Fi", 1.5), ("FG016 Sci-Fi Hunter", "Sci-Fi", 1.45),
    ("FG017 Fashion Agent A", "Fashion", 1.35), ("FG018 Fashion Agent B", "Fashion", 1.35),
    ("FG019 Fashion Agent C", "Fashion", 1.3), ("FG020 Fashion Agent D", "Fashion", 1.3),
    ("FG005 Deluxe", "Special", 1.55), ("FG009 Deluxe", "Special", 1.55),
    ("FG015 Deluxe", "Special", 1.55), ("FG001 Deluxe", "Special", 1.55),
    ("Outfit Pack Modern", "Accessories", 1.35, 65), ("Outfit Pack Fantasy", "Accessories", 1.35, 65),
    ("Head Sculpt Pack A", "Accessories", 1.3, 40), ("Weapon Pack Female", "Accessories", 1.3, 40),
    ("FG Luna Chrome", "Special", 1.5), ("FG Raven Night", "Special", 1.5),
    ("FG Crimson Glow", "Special", 1.55), ("FG Elf Chrome", "Special", 1.5),
    ("FG Android Neon", "Special", 1.5), ("FG Assassin Clear", "Special", 1.5),
    ("FG Fantasy Deluxe Pack", "Special", 1.5, 300), ("FG Modern Deluxe Pack", "Special", 1.5, 290),
    ("Flirty Girl Starter", "Special", 1.4, 270), ("Display Stand FG", "Accessories", 1.2, 28),
    ("FG Viper Deluxe", "Special", 1.5), ("FG Shadow Deluxe", "Special", 1.5),
    ("FG Mage Deluxe", "Special", 1.45),
]), 2016, 8, 2, 220)

add(data, "firegirl", "frg", pad45([
    ("FRG001 Tactical Girl A", "Tactical", 1.5), ("FRG002 Tactical Girl B", "Tactical", 1.5),
    ("FRG003 Tactical Girl C", "Tactical", 1.45), ("FRG004 Tactical Girl D", "Tactical", 1.45),
    ("FRG005 Sniper Girl", "Tactical", 1.55), ("FRG006 Medic Girl", "Tactical", 1.4),
    ("FRG007 Cyber Girl A", "Cyber", 1.5), ("FRG008 Cyber Girl B", "Cyber", 1.5),
    ("FRG009 Cyber Girl C", "Cyber", 1.45), ("FRG010 Cyber Girl Neon", "Cyber", 1.55),
    ("FRG011 School Agent A", "Agent", 1.4), ("FRG012 School Agent B", "Agent", 1.4),
    ("FRG013 School Agent C", "Agent", 1.35), ("FRG014 School Agent D", "Agent", 1.35),
    ("FRG015 Fantasy Warrior", "Fantasy", 1.5), ("FRG016 Fantasy Archer", "Fantasy", 1.5),
    ("FRG017 Fantasy Mage", "Fantasy", 1.45), ("FRG018 Fantasy Knight", "Fantasy", 1.5),
    ("FRG019 Lifestyle Agent A", "Lifestyle", 1.3), ("FRG020 Lifestyle Agent B", "Lifestyle", 1.3),
    ("FRG005 Deluxe", "Special", 1.55), ("FRG010 Deluxe", "Special", 1.55),
    ("FRG015 Deluxe", "Special", 1.55), ("FRG001 Deluxe", "Special", 1.55),
    ("Outfit Pack Tactical", "Accessories", 1.35, 60), ("Outfit Pack Cyber", "Accessories", 1.35, 60),
    ("Head Pack Fire Girl", "Accessories", 1.3, 38), ("Weapon Pack FRG", "Accessories", 1.3, 42),
    ("FRG Sniper Chrome", "Special", 1.55), ("FRG Cyber Neon", "Special", 1.55),
    ("FRG Fantasy Chrome", "Special", 1.5), ("FRG Tactical Night", "Special", 1.5),
    ("FRG Agent Clear", "Special", 1.4), ("FRG Cyber Clear", "Special", 1.5),
    ("Fire Girl Starter", "Special", 1.4, 260), ("Display Stand FRG", "Accessories", 1.2, 26),
    ("FRG Medic Deluxe", "Special", 1.45), ("FRG Archer Deluxe", "Special", 1.55),
    ("FRG Mage Deluxe", "Special", 1.45), ("FRG Knight Deluxe", "Special", 1.5),
    ("FRG Lifestyle Deluxe", "Special", 1.35),
]), 2017, 1, 2, 210)

add(data, "i8toys", "i8", pad45([
    ("i8-001 Operative Alpha", "Military", 1.45), ("i8-002 Operative Bravo", "Military", 1.45),
    ("i8-003 Operative Charlie", "Military", 1.4), ("i8-004 Operative Delta", "Military", 1.5),
    ("i8-005 Spec Ops Night", "Military", 1.55), ("i8-006 Spec Ops Desert", "Military", 1.5),
    ("i8-007 Female Operative A", "Military", 1.5), ("i8-008 Female Operative B", "Military", 1.45),
    ("i8-009 Sci-Fi Marine", "Sci-Fi", 1.5), ("i8-010 Sci-Fi Captain", "Sci-Fi", 1.5),
    ("i8-011 Sci-Fi Android", "Sci-Fi", 1.45), ("i8-012 Sci-Fi Hunter", "Sci-Fi", 1.45),
    ("i8-013 Fantasy Knight", "Fantasy", 1.5), ("i8-014 Fantasy Archer", "Fantasy", 1.45),
    ("i8-015 Fantasy Mage", "Fantasy", 1.4), ("i8-016 Fantasy Barbarian", "Fantasy", 1.45),
    ("i8-017 Crime Detective", "Crime", 1.4), ("i8-018 Crime Hitman", "Crime", 1.45),
    ("i8-019 Crime Boss", "Crime", 1.45), ("i8-020 Crime Undercover", "Crime", 1.4),
    ("i8-005 Deluxe", "Special", 1.55), ("i8-009 Deluxe", "Special", 1.55),
    ("i8-013 Deluxe", "Special", 1.55), ("i8-007 Deluxe", "Special", 1.55),
    ("Weapon Pack i8", "Accessories", 1.3, 40), ("Gear Pack i8", "Accessories", 1.3, 45),
    ("Head Pack i8", "Accessories", 1.25, 32), ("Outfit Pack i8", "Accessories", 1.35, 55),
    ("i8 Spec Ops Chrome", "Special", 1.55), ("i8 Sci-Fi Neon", "Special", 1.5),
    ("i8 Fantasy Chrome", "Special", 1.5), ("i8 Female Night", "Special", 1.5),
    ("i8 Crime Deluxe", "Special", 1.45), ("i8 Android Clear", "Special", 1.45),
    ("i8Toys Starter", "Special", 1.35, 250), ("Display Stand i8", "Accessories", 1.2, 24),
    ("i8 Desert Deluxe", "Special", 1.5), ("i8 Marine Deluxe", "Special", 1.5),
    ("i8 Archer Deluxe", "Special", 1.45), ("i8 Hitman Deluxe", "Special", 1.5),
    ("i8 Captain Deluxe", "Special", 1.5),
]), 2018, 3, 2, 195)

add(data, "nanmu", "nm", pad45([
    ("Nanmu T-Rex Apex", "Dinosaurs", 1.55), ("Nanmu T-Rex Hunter", "Dinosaurs", 1.55),
    ("Nanmu Velociraptor Pack", "Dinosaurs", 1.5), ("Nanmu Velociraptor Alpha", "Dinosaurs", 1.5),
    ("Nanmu Triceratops", "Dinosaurs", 1.45), ("Nanmu Stegosaurus", "Dinosaurs", 1.4),
    ("Nanmu Spinosaurus", "Dinosaurs", 1.55), ("Nanmu Brachiosaurus", "Dinosaurs", 1.4),
    ("Nanmu Allosaurus", "Dinosaurs", 1.45), ("Nanmu Carnotaurus", "Dinosaurs", 1.45),
    ("Nanmu Dilophosaurus", "Dinosaurs", 1.4), ("Nanmu Ankylosaurus", "Dinosaurs", 1.35),
    ("Nanmu Smilodon", "Prehistoric", 1.5), ("Nanmu Mammoth", "Prehistoric", 1.5),
    ("Nanmu Dire Wolf", "Prehistoric", 1.45), ("Nanmu Cave Bear", "Prehistoric", 1.4),
    ("Nanmu Modern Lion", "Wildlife", 1.45), ("Nanmu Modern Tiger", "Wildlife", 1.5),
    ("Nanmu Modern Wolf", "Wildlife", 1.4), ("Nanmu Modern Bear", "Wildlife", 1.4),
    ("T-Rex Apex Deluxe", "Special", 1.55), ("Spinosaurus Deluxe", "Special", 1.55),
    ("Velociraptor Deluxe", "Special", 1.55), ("Smilodon Deluxe", "Special", 1.55),
    ("T-Rex Chrome", "Special", 1.55), ("Tiger Chrome", "Special", 1.5),
    ("Base Pack Rocky", "Accessories", 1.25, 35), ("Base Pack Jungle", "Accessories", 1.25, 35),
    ("Effect Pack Roar", "Accessories", 1.2, 25), ("Diorama Pack Nest", "Accessories", 1.3, 55),
    ("T-Rex Battle Damaged", "Special", 1.5), ("Raptor Ghost", "Special", 1.5),
    ("Spinosaurus Clear", "Special", 1.5), ("Mammoth Winter", "Special", 1.5),
    ("Lion Night", "Special", 1.45), ("Wolf Snow", "Special", 1.4),
    ("Nanmu Starter Set", "Special", 1.4, 200), ("Display Stand Creature", "Accessories", 1.2, 30),
    ("Allosaurus Deluxe", "Special", 1.5), ("Triceratops Deluxe", "Special", 1.45),
    ("Dire Wolf Deluxe", "Special", 1.45),
]), 2018, 6, 2, 120)

add(data, "vtoys", "vt", pad45([
    ("VTOYS Male Body Standard", "Bodies", 1.4, 85), ("VTOYS Female Body Standard", "Bodies", 1.4, 85),
    ("VTOYS Male Body Athletic", "Bodies", 1.45, 95), ("VTOYS Female Body Athletic", "Bodies", 1.45, 95),
    ("VTOYS Male Body Slim", "Bodies", 1.35, 80), ("VTOYS Female Body Slim", "Bodies", 1.35, 80),
    ("VTOYS Head Male A", "Heads", 1.35, 32), ("VTOYS Head Male B", "Heads", 1.35, 32),
    ("VTOYS Head Female A", "Heads", 1.35, 32), ("VTOYS Head Female B", "Heads", 1.35, 32),
    ("VTOYS Military Figure A", "Military", 1.45, 160), ("VTOYS Military Figure B", "Military", 1.45, 160),
    ("VTOYS Military Figure C", "Military", 1.4, 155), ("VTOYS Military Figure D", "Military", 1.4, 155),
    ("VTOYS Fantasy Warrior", "Fantasy", 1.45, 165), ("VTOYS Fantasy Mage", "Fantasy", 1.4, 160),
    ("VTOYS Sci-Fi Trooper", "Sci-Fi", 1.45, 160), ("VTOYS Sci-Fi Android", "Sci-Fi", 1.45, 155),
    ("VTOYS Street Agent A", "Street", 1.4, 150), ("VTOYS Street Agent B", "Street", 1.4, 150),
    ("Male Body Deluxe", "Special", 1.5, 110), ("Female Body Deluxe", "Special", 1.5, 110),
    ("Military Deluxe A", "Special", 1.55, 190), ("Military Deluxe B", "Special", 1.5, 185),
    ("Hand Pack Male", "Accessories", 1.25, 22), ("Hand Pack Female", "Accessories", 1.25, 22),
    ("Foot Pack Standard", "Accessories", 1.2, 18), ("Neck Peg Pack", "Accessories", 1.15, 12),
    ("Head Pack Mixed", "Heads", 1.3, 55), ("Body Athletic Chrome", "Special", 1.45, 105),
    ("Fantasy Deluxe", "Special", 1.5, 185), ("Sci-Fi Deluxe", "Special", 1.5, 180),
    ("Street Deluxe", "Special", 1.45, 170), ("Military Night Ops", "Special", 1.55, 195),
    ("VTOYS Starter Body Set", "Special", 1.4, 200), ("Display Stand VTOYS", "Accessories", 1.2, 25),
    ("Female Military Deluxe", "Special", 1.55, 190), ("Android Neon", "Special", 1.45, 170),
    ("Mage Chrome", "Special", 1.4, 175), ("Trooper Clear", "Special", 1.4, 165),
    ("Athletic Pale Body", "Bodies", 1.4, 90),
]), 2019, 4, 2, 150)

# ========== DENSIFY (14) ==========
add(data, "hasbro", "hs", pad45([
    ("Marvel Legends Spider-Man Symbiote", "Marvel Legends", 1.55),
    ("Marvel Legends Venom Classic", "Marvel Legends", 1.55),
    ("Marvel Legends Carnage", "Marvel Legends", 1.5),
    ("Marvel Legends Miles Morales", "Marvel Legends", 1.5),
    ("Marvel Legends Spider-Gwen", "Marvel Legends", 1.5),
    ("Marvel Legends Iron Man Extremis", "Marvel Legends", 1.5),
    ("Marvel Legends Captain America WWII", "Marvel Legends", 1.5),
    ("Marvel Legends Wolverine Brown", "Marvel Legends", 1.55),
    ("Marvel Legends Magneto AOA", "Marvel Legends", 1.5),
    ("Marvel Legends Jean Grey", "Marvel Legends", 1.45),
    ("Black Series Luke Skywalker ROTJ", "Black Series", 1.5),
    ("Black Series Darth Vader ROTJ", "Black Series", 1.55),
    ("Black Series Din Djarin", "Black Series", 1.55),
    ("Black Series Grogu", "Black Series", 1.5),
    ("Black Series Ahsoka Tano", "Black Series", 1.5),
    ("Black Series Boba Fett Deluxe", "Black Series", 1.55),
    ("Classified Snake Eyes", "GI Joe Classified", 1.55),
    ("Classified Cobra Commander", "GI Joe Classified", 1.55),
    ("Classified Storm Shadow", "GI Joe Classified", 1.5),
    ("Classified Destro", "GI Joe Classified", 1.5),
    ("Classified Scarlett", "GI Joe Classified", 1.45),
    ("Classified Baroness", "GI Joe Classified", 1.5),
    ("Studio Series 86 Optimus", "Studio Series", 1.55),
    ("Studio Series 86 Megatron", "Studio Series", 1.55),
    ("Studio Series 86 Bumblebee", "Studio Series", 1.5),
    ("Studio Series 86 Starscream", "Studio Series", 1.5),
    ("Lightning Collection Red Ranger", "Lightning Collection", 1.5),
    ("Lightning Collection Green Ranger", "Lightning Collection", 1.55),
    ("Lightning Collection White Ranger", "Lightning Collection", 1.55),
    ("Lightning Collection Rita", "Lightning Collection", 1.45),
    ("ML BAF Annihilus Wave", "Marvel Legends", 1.45),
    ("ML BAF Bonebreaker Wave", "Marvel Legends", 1.4),
    ("BS Imperial Trooper Multipack", "Black Series", 1.45, 60),
    ("Classified Cobra Trooper 2-Pack", "GI Joe Classified", 1.4, 50),
    ("SS86 Dinobot Deluxe", "Studio Series", 1.55, 80),
    ("ML Retro Spider-Man", "Marvel Legends", 1.5),
    ("BS Clone Trooper Phase II", "Black Series", 1.5),
    ("Classified Firefly", "GI Joe Classified", 1.5),
    ("LC Zeo Ranger V", "Lightning Collection", 1.45),
    ("ML Deadpool Classic", "Marvel Legends", 1.55),
    ("BS Rey Jedi", "Black Series", 1.4),
    ("Classified Shipwreck", "GI Joe Classified", 1.4),
    ("SS86 Kup", "Studio Series", 1.4),
]), 2019, 1, 1, 24.99)

add(data, "mcfarlane", "mf", pad45([
    ("DC Multiverse Batman Hush", "DC Multiverse", 1.55),
    ("DC Multiverse Superman Hush", "DC Multiverse", 1.5),
    ("DC Multiverse Wonder Woman", "DC Multiverse", 1.45),
    ("DC Multiverse The Flash", "DC Multiverse", 1.45),
    ("DC Multiverse Aquaman", "DC Multiverse", 1.4),
    ("DC Multiverse Green Lantern", "DC Multiverse", 1.45),
    ("DC Multiverse Joker", "DC Multiverse", 1.55),
    ("DC Multiverse Harley Quinn", "DC Multiverse", 1.5),
    ("DC Multiverse Deathstroke", "DC Multiverse", 1.5),
    ("DC Multiverse Nightwing", "DC Multiverse", 1.45),
    ("DC Multiverse Red Hood", "DC Multiverse", 1.5),
    ("DC Multiverse Batgirl", "DC Multiverse", 1.4),
    ("Spawn Classic", "Spawn", 1.55), ("Spawn Violator", "Spawn", 1.5),
    ("Spawn Angela", "Spawn", 1.5), ("Spawn Medieval", "Spawn", 1.5),
    ("Spawn Gunslinger", "Spawn", 1.45), ("Spawn She-Spawn", "Spawn", 1.45),
    ("DC Multiverse Batman Who Laughs", "DC Multiverse", 1.55),
    ("DC Multiverse The Batman Movie", "DC Multiverse", 1.55),
    ("DC Multiverse Penguin Movie", "DC Multiverse", 1.45),
    ("DC Multiverse Catwoman Movie", "DC Multiverse", 1.45),
    ("Spawn Throne Deluxe", "Special", 1.55, 60),
    ("DC Multiverse Gold Label Batman", "Special", 1.55),
    ("DC Multiverse Gold Label Superman", "Special", 1.5),
    ("Spawn Bloody Exclusive", "Special", 1.55),
    ("McFarlane Megafigs Doomsday", "Megafigs", 1.5, 45),
    ("McFarlane Megafigs Darkseid", "Megafigs", 1.55, 50),
    ("DC Multiverse Black Adam", "DC Multiverse", 1.45),
    ("DC Multiverse Shazam", "DC Multiverse", 1.45),
    ("Spawn Redeemer", "Spawn", 1.45), ("Spawn Clown", "Spawn", 1.4),
    ("DC Multiverse Cyborg", "DC Multiverse", 1.4),
    ("DC Multiverse Raven", "DC Multiverse", 1.45),
    ("DC Multiverse Starfire", "DC Multiverse", 1.4),
    ("DC Multiverse Beast Boy", "DC Multiverse", 1.35),
    ("Spawn Mandarin Spawn", "Spawn", 1.5),
    ("DC Multiverse Injustice Batman", "DC Multiverse", 1.5),
    ("DC Multiverse Injustice Superman", "DC Multiverse", 1.5),
    ("DC Multiverse Page Punchers", "Special", 1.35, 30),
    ("DC Multiverse Platinum Edition", "Special", 1.5),
]), 2020, 1, 1, 22.99)

add(data, "mezco", "mz", pad45([
    ("One:12 Spider-Man Classic", "One:12 Collective", 1.55),
    ("One:12 Spider-Man Black Suit", "One:12 Collective", 1.55),
    ("One:12 Venom", "One:12 Collective", 1.55),
    ("One:12 Punisher", "One:12 Collective", 1.5),
    ("One:12 Daredevil", "One:12 Collective", 1.5),
    ("One:12 Wolverine", "One:12 Collective", 1.55),
    ("One:12 Magneto", "One:12 Collective", 1.5),
    ("One:12 Doctor Doom", "One:12 Collective", 1.55),
    ("One:12 Batman Sovereign Knight", "One:12 Collective", 1.55),
    ("One:12 Batman Ascending Knight", "One:12 Collective", 1.55),
    ("One:12 Superman", "One:12 Collective", 1.5),
    ("One:12 Joker", "One:12 Collective", 1.55),
    ("One:12 Harley Quinn", "One:12 Collective", 1.5),
    ("One:12 Rumble Society", "One:12 Collective", 1.45),
    ("One:12 Popeye", "One:12 Collective", 1.5),
    ("One:12 Freddy Krueger", "One:12 Collective", 1.55),
    ("One:12 Jason Voorhees", "One:12 Collective", 1.55),
    ("One:12 Michael Myers", "One:12 Collective", 1.55),
    ("One:12 Leatherface", "One:12 Collective", 1.5),
    ("One:12 Iron Man", "One:12 Collective", 1.55),
    ("One:12 Captain America", "One:12 Collective", 1.5),
    ("One:12 Thor", "One:12 Collective", 1.5),
    ("One:12 Hulk", "One:12 Collective", 1.55),
    ("One:12 Spider-Man Deluxe", "Special", 1.55),
    ("One:12 Batman Deluxe", "Special", 1.55),
    ("One:12 Wolverine Deluxe", "Special", 1.55),
    ("One:12 Joker Deluxe", "Special", 1.55),
    ("Mezco Hand Pack A", "Accessories", 1.25, 25),
    ("Mezco Hand Pack B", "Accessories", 1.25, 25),
    ("One:12 Green Goblin", "One:12 Collective", 1.55),
    ("One:12 Doc Ock", "One:12 Collective", 1.5),
    ("One:12 Moon Knight", "One:12 Collective", 1.55),
    ("One:12 Blade", "One:12 Collective", 1.5),
    ("One:12 Ghost Rider", "One:12 Collective", 1.55),
    ("One:12 Hellboy", "One:12 Collective", 1.55),
    ("One:12 Exclusive PX", "Special", 1.5),
    ("One:12 Exclusive SDCC", "Special", 1.55),
    ("One:12 Iron Man Deluxe", "Special", 1.55),
    ("One:12 Magneto Deluxe", "Special", 1.55),
    ("Mezco Display Base", "Accessories", 1.2, 20),
    ("One:12 Popeye Deluxe", "Special", 1.55),
]), 2016, 2, 2, 112)

add(data, "mafex", "mx", pad45([
    ("MAFEX Spider-Man Classic", "MAFEX", 1.55), ("MAFEX Spider-Man Black Suit", "MAFEX", 1.55),
    ("MAFEX Venom", "MAFEX", 1.55), ("MAFEX Iron Man", "MAFEX", 1.5),
    ("MAFEX Captain America", "MAFEX", 1.5), ("MAFEX Wolverine", "MAFEX", 1.55),
    ("MAFEX Deadpool", "MAFEX", 1.55), ("MAFEX Batman Hush", "MAFEX", 1.55),
    ("MAFEX Superman Hush", "MAFEX", 1.5), ("MAFEX Joker", "MAFEX", 1.55),
    ("MAFEX Harley Quinn", "MAFEX", 1.5), ("MAFEX Catwoman", "MAFEX", 1.45),
    ("MAFEX Batman The Batman", "MAFEX", 1.55), ("MAFEX T-800", "MAFEX", 1.55),
    ("MAFEX RoboCop", "MAFEX", 1.5), ("MAFEX Akira Kaneda", "MAFEX", 1.55),
    ("MAFEX Akira Tetsuo", "MAFEX", 1.5), ("MAFEX Evangelion Unit-01", "MAFEX", 1.55),
    ("MAFEX Evangelion Unit-02", "MAFEX", 1.5), ("MAFEX Gundam RX-78", "MAFEX", 1.5),
    ("MAFEX Spider-Man Deluxe", "Special", 1.55), ("MAFEX Batman Deluxe", "Special", 1.55),
    ("MAFEX Wolverine Deluxe", "Special", 1.55), ("MAFEX Deadpool Deluxe", "Special", 1.55),
    ("MAFEX Effect Parts Web", "Accessories", 1.3, 25), ("MAFEX Effect Parts Energy", "Accessories", 1.3, 25),
    ("MAFEX Stand Pack", "Accessories", 1.2, 18), ("MAFEX Magneto", "MAFEX", 1.5),
    ("MAFEX Cyclops", "MAFEX", 1.45), ("MAFEX Jean Grey", "MAFEX", 1.45),
    ("MAFEX Nightcrawler", "MAFEX", 1.5), ("MAFEX Batman Hush Chase", "Special", 1.55),
    ("MAFEX Joker Chase", "Special", 1.55), ("MAFEX T-800 Battle Damaged", "Special", 1.55),
    ("MAFEX Unit-01 Awakened", "Special", 1.55), ("MAFEX Kaneda Bike Set", "Special", 1.55, 180),
    ("MAFEX Spider-Man Miles", "MAFEX", 1.5), ("MAFEX Spider-Gwen", "MAFEX", 1.5),
    ("MAFEX Punisher", "MAFEX", 1.45), ("MAFEX Daredevil", "MAFEX", 1.5),
    ("MAFEX Green Goblin", "MAFEX", 1.55),
]), 2015, 4, 2, 95)

add(data, "storm", "st", pad45([
    ("Storm Ryu", "Street Fighter", 1.55), ("Storm Ken", "Street Fighter", 1.5),
    ("Storm Chun-Li", "Street Fighter", 1.55), ("Storm Guile", "Street Fighter", 1.45),
    ("Storm Akuma", "Street Fighter", 1.55), ("Storm M. Bison", "Street Fighter", 1.5),
    ("Storm Cammy", "Street Fighter", 1.5), ("Storm Dhalsim", "Street Fighter", 1.4),
    ("Storm Zangief", "Street Fighter", 1.4), ("Storm Vega", "Street Fighter", 1.45),
    ("Storm Scorpion", "Mortal Kombat", 1.55), ("Storm Sub-Zero", "Mortal Kombat", 1.55),
    ("Storm Raiden", "Mortal Kombat", 1.5), ("Storm Liu Kang", "Mortal Kombat", 1.5),
    ("Storm Kitana", "Mortal Kombat", 1.5), ("Storm Mileena", "Mortal Kombat", 1.5),
    ("Storm Kung Lao", "Mortal Kombat", 1.45), ("Storm Johnny Cage", "Mortal Kombat", 1.4),
    ("Storm Iori Yagami", "King of Fighters", 1.5), ("Storm Kyo Kusanagi", "King of Fighters", 1.5),
    ("Storm Terry Bogard", "King of Fighters", 1.5), ("Storm Mai Shiranui", "King of Fighters", 1.55),
    ("Storm Ryu Deluxe", "Special", 1.55), ("Storm Chun-Li Deluxe", "Special", 1.55),
    ("Storm Akuma Deluxe", "Special", 1.55), ("Storm Scorpion Deluxe", "Special", 1.55),
    ("Storm Sub-Zero Deluxe", "Special", 1.55), ("Storm Mai Deluxe", "Special", 1.55),
    ("Storm Effect Hadoken", "Accessories", 1.35, 30), ("Storm Effect Ice", "Accessories", 1.35, 30),
    ("Storm Stand Pack", "Accessories", 1.2, 20), ("Storm Weapon Pack MK", "Accessories", 1.3, 35),
    ("Storm Ryu Chrome", "Special", 1.55), ("Storm Akuma Demon", "Special", 1.55),
    ("Storm Cammy Deluxe", "Special", 1.55), ("Storm Kitana Deluxe", "Special", 1.55),
    ("Storm Iori Deluxe", "Special", 1.55), ("Storm Terry Deluxe", "Special", 1.5),
    ("Storm Bison Deluxe", "Special", 1.55), ("Storm Raiden Deluxe", "Special", 1.55),
    ("Storm Mileena Deluxe", "Special", 1.55),
]), 2015, 1, 2, 110)

add(data, "hiya", "hy2", pad45([
    ("Hiya Godzilla 2014", "Godzilla", 1.55), ("Hiya Godzilla 2019", "Godzilla", 1.55),
    ("Hiya Godzilla Evolved", "Godzilla", 1.55), ("Hiya Kong", "Godzilla", 1.5),
    ("Hiya Mechagodzilla", "Godzilla", 1.55), ("Hiya Ghidorah", "Godzilla", 1.55),
    ("Hiya Rodan", "Godzilla", 1.45), ("Hiya Mothra", "Godzilla", 1.45),
    ("Hiya Exquisite Mini Godzilla", "Exquisite Mini", 1.5), ("Hiya Exquisite Mini Kong", "Exquisite Mini", 1.45),
    ("Hiya Exquisite Mini Alien", "Exquisite Mini", 1.5), ("Hiya Exquisite Mini Predator", "Exquisite Mini", 1.5),
    ("Hiya Exquisite Super Series Alien", "Exquisite Super", 1.55), ("Hiya Exquisite Super Predator", "Exquisite Super", 1.55),
    ("Hiya RoboCop", "Movie", 1.5), ("Hiya T-800", "Movie", 1.55),
    ("Hiya T-1000", "Movie", 1.55), ("Hiya Judge Dredd", "Movie", 1.45),
    ("Hiya Colonial Marine", "Aliens", 1.5), ("Hiya Alien Warrior", "Aliens", 1.55),
    ("Hiya Godzilla Deluxe", "Special", 1.55), ("Hiya Kong Deluxe", "Special", 1.55),
    ("Hiya Mechagodzilla Deluxe", "Special", 1.55), ("Hiya Ghidorah Deluxe", "Special", 1.55),
    ("Hiya Effect Atomic Breath", "Accessories", 1.35, 30), ("Hiya Base City", "Accessories", 1.3, 40),
    ("Hiya Stand Pack", "Accessories", 1.2, 18), ("Hiya Weapon Pack Marine", "Accessories", 1.3, 28),
    ("Hiya Godzilla Clear", "Special", 1.5), ("Hiya Kong Battle Damaged", "Special", 1.5),
    ("Hiya Alien Chrome", "Special", 1.55), ("Hiya Predator Jungle", "Special", 1.55),
    ("Hiya T-800 Battle Damaged", "Special", 1.55), ("Hiya RoboCop Chrome", "Special", 1.5),
    ("Hiya Rodan Deluxe", "Special", 1.45), ("Hiya Mothra Deluxe", "Special", 1.45),
    ("Hiya Colonial Marine Deluxe", "Special", 1.55), ("Hiya Judge Dredd Deluxe", "Special", 1.5),
    ("Hiya T-1000 Deluxe", "Special", 1.55), ("Hiya Alien Warrior Deluxe", "Special", 1.55),
    ("Hiya Evolved Chrome", "Special", 1.55),
]), 2019, 5, 2, 90)

add(data, "mondo", "md", pad45([
    ("Mondo He-Man 1/6", "MotU 1/6", 1.55), ("Mondo Skeletor 1/6", "MotU 1/6", 1.55),
    ("Mondo Teela 1/6", "MotU 1/6", 1.5), ("Mondo Man-At-Arms 1/6", "MotU 1/6", 1.45),
    ("Mondo Beast Man 1/6", "MotU 1/6", 1.45), ("Mondo Evil-Lyn 1/6", "MotU 1/6", 1.5),
    ("Mondo Leonardo 1/6", "TMNT 1/6", 1.55), ("Mondo Raphael 1/6", "TMNT 1/6", 1.55),
    ("Mondo Donatello 1/6", "TMNT 1/6", 1.5), ("Mondo Michelangelo 1/6", "TMNT 1/6", 1.5),
    ("Mondo Shredder 1/6", "TMNT 1/6", 1.55), ("Mondo Splinter 1/6", "TMNT 1/6", 1.45),
    ("Mondo Soft Vinyl He-Man", "Soft Vinyl AF", 1.4), ("Mondo Soft Vinyl Skeletor", "Soft Vinyl AF", 1.4),
    ("Mondo Soft Vinyl Leonardo", "Soft Vinyl AF", 1.4), ("Mondo Soft Vinyl Raphael", "Soft Vinyl AF", 1.4),
    ("Mondo RoboCop 1/6", "Movie 1/6", 1.55), ("Mondo T-800 1/6", "Movie 1/6", 1.55),
    ("Mondo Alien 1/6", "Movie 1/6", 1.55), ("Mondo Predator 1/6", "Movie 1/6", 1.55),
    ("Mondo He-Man Deluxe", "Special", 1.55), ("Mondo Skeletor Deluxe", "Special", 1.55),
    ("Mondo Leonardo Deluxe", "Special", 1.55), ("Mondo Shredder Deluxe", "Special", 1.55),
    ("Mondo Weapon Pack MotU", "Accessories", 1.3, 45), ("Mondo Weapon Pack TMNT", "Accessories", 1.3, 45),
    ("Mondo Stand Pack", "Accessories", 1.2, 28), ("Mondo Soft Goods Cape", "Accessories", 1.25, 35),
    ("Mondo He-Man Chrome", "Special", 1.55), ("Mondo Skeletor Glow", "Special", 1.55),
    ("Mondo RoboCop Deluxe", "Special", 1.55), ("Mondo T-800 Deluxe", "Special", 1.55),
    ("Mondo Alien Deluxe", "Special", 1.55), ("Mondo Predator Deluxe", "Special", 1.55),
    ("Mondo Teela Deluxe", "Special", 1.55), ("Mondo Evil-Lyn Deluxe", "Special", 1.55),
    ("Mondo Splinter Deluxe", "Special", 1.5), ("Mondo Bebop 1/6", "TMNT 1/6", 1.45),
    ("Mondo Rocksteady 1/6", "TMNT 1/6", 1.45), ("Mondo Soft Vinyl Chase", "Special", 1.45),
    ("Mondo Battle Cat Soft Goods", "Special", 1.5, 200),
]), 2018, 2, 2, 300)

add(data, "shfiguarts", "sh", pad45([
    ("SHF Goku Ultra Instinct", "Dragon Ball", 1.55), ("SHF Vegeta Ultra Ego", "Dragon Ball", 1.55),
    ("SHF Gohan Beast", "Dragon Ball", 1.5), ("SHF Piccolo Super Hero", "Dragon Ball", 1.45),
    ("SHF Broly Full Power", "Dragon Ball", 1.55), ("SHF Jiren", "Dragon Ball", 1.5),
    ("SHF Naruto Sage", "Naruto", 1.55), ("SHF Sasuke Rinnegan", "Naruto", 1.55),
    ("SHF Kakashi", "Naruto", 1.45), ("SHF Itachi", "Naruto", 1.5),
    ("SHF Luffy Gear 5", "One Piece", 1.55), ("SHF Zoro", "One Piece", 1.5),
    ("SHF Sanji", "One Piece", 1.45), ("SHF Law", "One Piece", 1.45),
    ("SHF Iron Man Mark 85", "Marvel", 1.55), ("SHF Spider-Man No Way Home", "Marvel", 1.55),
    ("SHF Doctor Strange", "Marvel", 1.5), ("SHF Captain America", "Marvel", 1.45),
    ("SHF Batman The Batman", "DC", 1.55), ("SHF Superman", "DC", 1.5),
    ("SHF Ultraman Rising", "Ultraman", 1.5), ("SHF Kamen Rider", "Kamen Rider", 1.55),
    ("SHF Darth Vader", "Star Wars", 1.55), ("SHF Luke Skywalker", "Star Wars", 1.5),
    ("SHF Goku Deluxe", "Special", 1.55), ("SHF Luffy Deluxe", "Special", 1.55),
    ("SHF Iron Man Deluxe", "Special", 1.55), ("SHF Batman Deluxe", "Special", 1.55),
    ("SHF Effect Aura", "Accessories", 1.35, 28), ("SHF Effect Web", "Accessories", 1.3, 25),
    ("SHF Stand Tamashii", "Accessories", 1.25, 20), ("SHF Option Parts Pack", "Accessories", 1.3, 30),
    ("SHF Goku Clear", "Special", 1.5), ("SHF Vegeta Chrome", "Special", 1.55),
    ("SHF Naruto Deluxe", "Special", 1.55), ("SHF Sasuke Deluxe", "Special", 1.55),
    ("SHF Spider-Man Deluxe", "Special", 1.55), ("SHF Kamen Rider Deluxe", "Special", 1.55),
    ("SHF Broly Deluxe", "Special", 1.55), ("SHF Zoro Deluxe", "Special", 1.55),
    ("SHF Vader Deluxe", "Special", 1.55),
]), 2018, 1, 1, 75)

add(data, "kaiyodo", "ky", pad45([
    ("Amazing Yamaguchi Spider-Man", "Amazing Yamaguchi", 1.55),
    ("Amazing Yamaguchi Deadpool", "Amazing Yamaguchi", 1.55),
    ("Amazing Yamaguchi Wolverine", "Amazing Yamaguchi", 1.55),
    ("Amazing Yamaguchi Batman", "Amazing Yamaguchi", 1.55),
    ("Amazing Yamaguchi Joker", "Amazing Yamaguchi", 1.55),
    ("Amazing Yamaguchi Harley Quinn", "Amazing Yamaguchi", 1.5),
    ("Amazing Yamaguchi Iron Man", "Amazing Yamaguchi", 1.5),
    ("Amazing Yamaguchi Venom", "Amazing Yamaguchi", 1.55),
    ("Amazing Yamaguchi Carnage", "Amazing Yamaguchi", 1.5),
    ("Amazing Yamaguchi Cyclops", "Amazing Yamaguchi", 1.45),
    ("Revoltech Evangelion Unit-01", "Revoltech", 1.55),
    ("Revoltech Evangelion Unit-02", "Revoltech", 1.5),
    ("Revoltech Optimus Prime", "Revoltech", 1.5),
    ("Revoltech Megatron", "Revoltech", 1.5),
    ("Revoltech Godzilla", "Revoltech", 1.55),
    ("Revoltech Kong", "Revoltech", 1.45),
    ("Revoltech Guts", "Revoltech", 1.55),
    ("Revoltech Griffith", "Revoltech", 1.5),
    ("Amazing Yamaguchi Spider-Man Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Deadpool Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Batman Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Wolverine Deluxe", "Special", 1.55),
    ("AY Effect Web", "Accessories", 1.3, 22), ("AY Effect Energy", "Accessories", 1.3, 22),
    ("Revoltech Stand", "Accessories", 1.2, 15), ("AY Option Hands", "Accessories", 1.25, 18),
    ("Amazing Yamaguchi Venom Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Joker Deluxe", "Special", 1.55),
    ("Revoltech Unit-01 Awakened", "Special", 1.55),
    ("Revoltech Guts Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Harley Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Iron Man Deluxe", "Special", 1.55),
    ("Revoltech Godzilla Deluxe", "Special", 1.55),
    ("Revoltech Optimus Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Carnage Deluxe", "Special", 1.55),
    ("AY Batman Who Laughs", "Amazing Yamaguchi", 1.55),
    ("AY Nightcrawler", "Amazing Yamaguchi", 1.5),
    ("AY Magneto", "Amazing Yamaguchi", 1.5),
    ("Kaiyodo Starter AY", "Special", 1.4, 130),
    ("Revoltech Megatron Deluxe", "Special", 1.55),
    ("Amazing Yamaguchi Spider-Man Black", "Special", 1.55),
]), 2016, 3, 2, 95)

add(data, "figma", "fgm", pad45([
    ("figma Link Tears of the Kingdom", "The Legend of Zelda", 1.55),
    ("figma Zelda Tears", "The Legend of Zelda", 1.5),
    ("figma Samus Aran", "Metroid", 1.55),
    ("figma Kirby", "Kirby", 1.45),
    ("figma Cloud Strife", "Final Fantasy", 1.55),
    ("figma Sephiroth", "Final Fantasy", 1.55),
    ("figma Saber", "Fate", 1.5),
    ("figma Archer EMIYA", "Fate", 1.45),
    ("figma Hatsune Miku", "Vocaloid", 1.5),
    ("figma Asuka Langley", "Evangelion", 1.55),
    ("figma Rei Ayanami", "Evangelion", 1.5),
    ("figma Shinji Ikari", "Evangelion", 1.4),
    ("figma Guts", "Berserk", 1.55),
    ("figma Casca", "Berserk", 1.45),
    ("figma Dovahkiin", "The Elder Scrolls", 1.5),
    ("figma Geralt", "The Witcher", 1.55),
    ("figma V", "Cyberpunk", 1.5),
    ("figma 2B", "Nier", 1.55),
    ("figma Joker Persona", "Persona", 1.5),
    ("figma Crow Persona", "Persona", 1.45),
    ("figma Link Deluxe", "Special", 1.55),
    ("figma Samus Deluxe", "Special", 1.55),
    ("figma Cloud Deluxe", "Special", 1.55),
    ("figma Guts Deluxe", "Special", 1.55),
    ("figma Effect Slash", "Accessories", 1.3, 20),
    ("figma Effect Magic", "Accessories", 1.3, 20),
    ("figma Stand Armed", "Accessories", 1.25, 18),
    ("figma Option Body", "Accessories", 1.3, 35),
    ("figma 2B Deluxe", "Special", 1.55),
    ("figma Geralt Deluxe", "Special", 1.55),
    ("figma Saber Deluxe", "Special", 1.55),
    ("figma Miku Deluxe", "Special", 1.55),
    ("figma Asuka Deluxe", "Special", 1.55),
    ("figma Sephiroth Deluxe", "Special", 1.55),
    ("figma V Deluxe", "Special", 1.55),
    ("figma Joker Deluxe", "Special", 1.55),
    ("figma Zelda Deluxe", "Special", 1.55),
    ("figma Kirby Deluxe", "Special", 1.45),
    ("figma Rei Deluxe", "Special", 1.55),
    ("figma Casca Deluxe", "Special", 1.5),
    ("figma Dovahkiin Deluxe", "Special", 1.55),
]), 2017, 2, 1, 75)

add(data, "jakks", "jk", pad45([
    ("Sonic 2.5 Wave Modern Sonic", "Sonic", 1.4, 8),
    ("Sonic 2.5 Wave Shadow", "Sonic", 1.45, 8),
    ("Sonic 2.5 Wave Knuckles", "Sonic", 1.4, 8),
    ("Sonic 2.5 Wave Tails", "Sonic", 1.35, 8),
    ("Sonic 2.5 Wave Amy", "Sonic", 1.35, 8),
    ("Sonic 2.5 Wave Metal Sonic", "Sonic", 1.45, 8),
    ("Sonic 4 Inch Movie Sonic", "Sonic Movie", 1.5, 12),
    ("Sonic 4 Inch Movie Shadow", "Sonic Movie", 1.55, 12),
    ("Sonic 4 Inch Movie Knuckles", "Sonic Movie", 1.5, 12),
    ("Sonic 5 Inch Super Sonic", "Sonic", 1.55, 15),
    ("Nintendo 2.5 Mario", "Nintendo", 1.4, 8),
    ("Nintendo 2.5 Luigi", "Nintendo", 1.35, 8),
    ("Nintendo 2.5 Yoshi", "Nintendo", 1.35, 8),
    ("Nintendo 2.5 Bowser", "Nintendo", 1.45, 8),
    ("Nintendo 4 Inch Mario", "Nintendo", 1.45, 12),
    ("Nintendo 4 Inch Link", "Nintendo", 1.5, 12),
    ("WWE Superstars Series", "WWE", 1.35, 10),
    ("WWE Bend N Bash", "WWE", 1.3, 12),
    ("Primal Age He-Man", "Primal Age", 1.4, 20),
    ("Primal Age Skeletor", "Primal Age", 1.45, 20),
    ("Primal Age Beast Man", "Primal Age", 1.35, 20),
    ("Primal Age Man-At-Arms", "Primal Age", 1.35, 20),
    ("Sonic Chase Glow", "Special", 1.5, 10),
    ("Sonic Movie Deluxe", "Special", 1.55, 25),
    ("Nintendo Mario Chase", "Special", 1.45, 10),
    ("Nintendo Link Deluxe", "Special", 1.55, 18),
    ("WWE Chase Figure", "Special", 1.4, 12),
    ("Primal Age Deluxe He-Man", "Special", 1.5, 30),
    ("Sonic Accessory Pack", "Accessories", 1.2, 8),
    ("Nintendo Accessory Pack", "Accessories", 1.2, 8),
    ("Sonic 2.5 Wave Rouge", "Sonic", 1.35, 8),
    ("Sonic 2.5 Wave Eggman", "Sonic", 1.4, 8),
    ("Nintendo 2.5 Peach", "Nintendo", 1.4, 8),
    ("Nintendo 4 Inch Samus", "Nintendo", 1.5, 12),
    ("Primal Age Mer-Man", "Primal Age", 1.35, 20),
    ("Primal Age Stratos", "Primal Age", 1.35, 20),
    ("Sonic Super Form Deluxe", "Special", 1.55, 20),
    ("Shadow Movie Deluxe", "Special", 1.55, 25),
    ("JAKKS Starter Sonic", "Special", 1.35, 35),
    ("Primal Age Starter", "Special", 1.4, 55),
    ("Sonic Metal Glow", "Special", 1.5, 10),
]), 2019, 1, 1, 12.99)

add(data, "joytoy", "jt2", pad45([
    ("JoyToy Ultramarines Intercessor", "Warhammer 40K", 1.55),
    ("JoyToy Ultramarines Captain", "Warhammer 40K", 1.55),
    ("JoyToy Blood Angels", "Warhammer 40K", 1.5),
    ("JoyToy Space Wolves", "Warhammer 40K", 1.5),
    ("JoyToy Black Templars", "Warhammer 40K", 1.55),
    ("JoyToy Dark Angels", "Warhammer 40K", 1.5),
    ("JoyToy Chaos Space Marine", "Warhammer 40K", 1.55),
    ("JoyToy Ork Boy", "Warhammer 40K", 1.45),
    ("JoyToy Necron Warrior", "Warhammer 40K", 1.5),
    ("JoyToy Tyranid Warrior", "Warhammer 40K", 1.55),
    ("JoyToy Sisters of Battle", "Warhammer 40K", 1.5),
    ("JoyToy Astra Militarum", "Warhammer 40K", 1.4),
    ("JoyToy Dark Source Scout", "Dark Source", 1.45),
    ("JoyToy Dark Source Heavy", "Dark Source", 1.45),
    ("JoyToy Dark Source Commander", "Dark Source", 1.5),
    ("JoyToy Dark Source Sniper", "Dark Source", 1.45),
    ("JoyToy Saluk Female Fighter", "Dark Source", 1.5),
    ("JoyToy Hardcore Coldplay", "Dark Source", 1.4),
    ("JoyToy 1/18 Mecha Pilot", "1/18 Mecha", 1.45),
    ("JoyToy 1/18 Mecha Suit", "1/18 Mecha", 1.55),
    ("Ultramarines Deluxe", "Special", 1.55),
    ("Chaos Deluxe", "Special", 1.55),
    ("Tyranid Deluxe", "Special", 1.55),
    ("Dark Source Deluxe", "Special", 1.55),
    ("Weapon Pack 40K", "Accessories", 1.3, 25),
    ("Weapon Pack Dark Source", "Accessories", 1.3, 25),
    ("Base Pack Battlefield", "Accessories", 1.25, 20),
    ("Mecha Option Parts", "Accessories", 1.35, 40),
    ("Black Templars Deluxe", "Special", 1.55),
    ("Necron Deluxe", "Special", 1.55),
    ("Sisters Deluxe", "Special", 1.55),
    ("Space Wolves Deluxe", "Special", 1.55),
    ("Blood Angels Deluxe", "Special", 1.55),
    ("Ork Deluxe", "Special", 1.5),
    ("Mecha Suit Deluxe", "Special", 1.55),
    ("Dark Source Commander Deluxe", "Special", 1.55),
    ("JoyToy Starter 40K", "Special", 1.4, 90),
    ("Ultramarines Captain Chrome", "Special", 1.55),
    ("Chaos Chrome", "Special", 1.55),
    ("Saluk Deluxe", "Special", 1.55),
    ("Dark Angels Deluxe", "Special", 1.55),
]), 2020, 2, 1, 45)

add(data, "sentinel", "sn", pad45([
    ("Fighting Armor Iron Man", "Fighting Armor", 1.55),
    ("Fighting Armor Captain America", "Fighting Armor", 1.5),
    ("Fighting Armor Thor", "Fighting Armor", 1.5),
    ("Fighting Armor Spider-Man", "Fighting Armor", 1.55),
    ("Fighting Armor Wolverine", "Fighting Armor", 1.55),
    ("Fighting Armor Deadpool", "Fighting Armor", 1.5),
    ("Fighting Armor Magneto", "Fighting Armor", 1.5),
    ("Fighting Armor Doctor Doom", "Fighting Armor", 1.55),
    ("Riobot Voltron", "Riobot", 1.55),
    ("Riobot Getter 1", "Riobot", 1.55),
    ("Riobot Getter 2", "Riobot", 1.45),
    ("Riobot Getter 3", "Riobot", 1.45),
    ("Riobot Mazinger Z", "Riobot", 1.55),
    ("Riobot Great Mazinger", "Riobot", 1.5),
    ("Riobot Grendizer", "Riobot", 1.55),
    ("Wonderful Acts Figure A", "Wonderful Acts", 1.4),
    ("Wonderful Acts Figure B", "Wonderful Acts", 1.4),
    ("Wonderful Acts Figure C", "Wonderful Acts", 1.35),
    ("Fighting Armor Iron Man Deluxe", "Special", 1.55),
    ("Fighting Armor Spider-Man Deluxe", "Special", 1.55),
    ("Riobot Voltron Deluxe", "Special", 1.55),
    ("Riobot Getter Deluxe", "Special", 1.55),
    ("Fighting Armor Effect Pack", "Accessories", 1.3, 35),
    ("Riobot Effect Pack", "Accessories", 1.35, 45),
    ("Sentinel Stand Pack", "Accessories", 1.2, 25),
    ("Option Parts Fighting Armor", "Accessories", 1.3, 40),
    ("Fighting Armor Wolverine Deluxe", "Special", 1.55),
    ("Fighting Armor Doom Deluxe", "Special", 1.55),
    ("Riobot Mazinger Deluxe", "Special", 1.55),
    ("Riobot Grendizer Deluxe", "Special", 1.55),
    ("Fighting Armor Cap Deluxe", "Special", 1.55),
    ("Fighting Armor Thor Deluxe", "Special", 1.55),
    ("Riobot Great Mazinger Deluxe", "Special", 1.55),
    ("Wonderful Acts Deluxe", "Special", 1.45),
    ("Fighting Armor Deadpool Deluxe", "Special", 1.55),
    ("Fighting Armor Magneto Deluxe", "Special", 1.55),
    ("Sentinel Starter FA", "Special", 1.4, 180),
    ("Sentinel Starter Riobot", "Special", 1.45, 250),
    ("Fighting Armor Chrome Iron Man", "Special", 1.55),
    ("Riobot Voltron Chrome", "Special", 1.55),
    ("Fighting Armor Exclusive", "Special", 1.55),
]), 2016, 4, 2, 120)

add(data, "kenner", "kn", pad45([
    ("Super Powers Superman", "Super Powers", 1.5),
    ("Super Powers Batman", "Super Powers", 1.55),
    ("Super Powers Robin", "Super Powers", 1.4),
    ("Super Powers Wonder Woman", "Super Powers", 1.45),
    ("Super Powers Flash", "Super Powers", 1.45),
    ("Super Powers Green Lantern", "Super Powers", 1.45),
    ("Super Powers Aquaman", "Super Powers", 1.4),
    ("Super Powers Joker", "Super Powers", 1.55),
    ("Super Powers Penguin", "Super Powers", 1.4),
    ("Super Powers Riddler", "Super Powers", 1.4),
    ("Super Powers Lex Luthor", "Super Powers", 1.45),
    ("Super Powers Darkseid", "Super Powers", 1.55),
    ("Super Powers Cyborg", "Super Powers", 1.4),
    ("Super Powers Firestorm", "Super Powers", 1.35),
    ("Super Powers Hawkman", "Super Powers", 1.4),
    ("Super Powers Martian Manhunter", "Super Powers", 1.45),
    ("Batman 89 Movie Batman", "Batman Movie", 1.55),
    ("Batman 89 Movie Joker", "Batman Movie", 1.55),
    ("Batman Returns Catwoman", "Batman Movie", 1.5),
    ("Batman Returns Penguin", "Batman Movie", 1.45),
    ("Batman Forever Batman", "Batman Movie", 1.4),
    ("Batman Forever Robin", "Batman Movie", 1.35),
    ("Batman and Robin Batman", "Batman Movie", 1.35),
    ("Batman and Robin Mr Freeze", "Batman Movie", 1.4),
    ("Super Powers Superman Chase", "Special", 1.55),
    ("Super Powers Batman Chase", "Special", 1.55),
    ("Super Powers Darkseid Deluxe", "Special", 1.55),
    ("Batman 89 Deluxe", "Special", 1.55),
    ("Kenner Accessory Pack SP", "Accessories", 1.2, 10),
    ("Kenner Vehicle Batmobile 89", "Accessories", 1.5, 40),
    ("Super Powers Green Arrow", "Super Powers", 1.4),
    ("Super Powers Red Tornado", "Super Powers", 1.35),
    ("Super Powers Brainiac", "Super Powers", 1.45),
    ("Super Powers Kalibak", "Super Powers", 1.4),
    ("Super Powers Desaad", "Super Powers", 1.35),
    ("Super Powers Steppenwolf", "Super Powers", 1.4),
    ("Batman 89 Batman Chase", "Special", 1.55),
    ("Batman 89 Joker Chase", "Special", 1.55),
    ("Batman Returns Catwoman Deluxe", "Special", 1.55),
    ("Super Powers 2-Pack Heroes", "Special", 1.45, 30),
    ("Super Powers Plastic Man", "Super Powers", 1.35),
]), 1984, 1, 2, 5.99)

OUT.write_text(json.dumps(data, indent=2) + "\n")
total = sum(len(v) for v in data.values())
print(f"Wrote {OUT.name}: {len(data)} keys, {total} rows")
for k, v in data.items():
    print(f"  {k}: {len(v)}")
