"""DC toys gap wave16 — Kenner Batman: The Animated Series family (1992-1997:
Series 1-4, Mail-Away, Deluxe, Crime Squad, Duo Force, vehicles, plus Mask of
the Phantasm and The Adventures of Batman & Robin) and McFarlane DC Retro
(Batman '66 / Batman '66 Comic / The New Adventures of Batman / Super
Friends, 2021-2025; 2026 waves and playsets skipped).

Source: ActionFigure411 checklists (kenner-batman-animated-series,
retro-66), snapshot in _af411_dc_checklists_wave16.json; rows generated by
_gen_wave16_data.py. Release year and original retail from AF411. Existing
DC Retro rows (same character + year) skipped. No imageUrl / no GTINs.
"""
from __future__ import annotations
import json
from pathlib import Path

_DATA = Path(__file__).with_name("_dc_gap_wave16_data.json")

def build_dc_gap_wave16() -> list[dict]:
    if not _DATA.is_file():
        return []
    return json.loads(_DATA.read_text())
