/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ComicsIndexRouteImport } from './routes/comics/index'
import { Route as ComicsComicIdRouteImport } from './routes/comics/$comicId'
import { Route as FiguresIndexRouteImport } from './routes/figures/index'
import { Route as FiguresFigureIdRouteImport } from './routes/figures/$figureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsIndexRoute = ComicsIndexRouteImport.update({
  id: '/comics/',
  path: '/comics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsComicIdRoute = ComicsComicIdRouteImport.update({
  id: '/comics/$comicId',
  path: '/comics/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresFigureIdRoute = FiguresFigureIdRouteImport.update({
  id: '/figures/$figureId',
  path: '/figures/$figureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/scan': typeof ScanRoute
  '/wishlist': typeof WishlistRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/comics/': typeof ComicsIndexRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/scan': typeof ScanRoute
  '/wishlist': typeof WishlistRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/comics': typeof ComicsIndexRoute
  '/figures': typeof FiguresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/scan': typeof ScanRoute
  '/wishlist': typeof WishlistRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/comics/': typeof ComicsIndexRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/scan'
    | '/wishlist'
    | '/comics/$comicId'
    | '/figures/$figureId'
    | '/comics/'
    | '/figures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/scan'
    | '/wishlist'
    | '/comics/$comicId'
    | '/figures/$figureId'
    | '/comics'
    | '/figures'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/scan'
    | '/wishlist'
    | '/comics/$comicId'
    | '/figures/$figureId'
    | '/comics/'
    | '/figures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  ScanRoute: typeof ScanRoute
  WishlistRoute: typeof WishlistRoute
  ComicsComicIdRoute: typeof ComicsComicIdRoute
  FiguresFigureIdRoute: typeof FiguresFigureIdRoute
  ComicsIndexRoute: typeof ComicsIndexRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics/': {
      id: '/comics/'
      path: '/comics'
      fullPath: '/comics/'
      preLoaderRoute: typeof ComicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics/$comicId': {
      id: '/comics/$comicId'
      path: '/comics/$comicId'
      fullPath: '/comics/$comicId'
      preLoaderRoute: typeof ComicsComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/figures'
      fullPath: '/figures/'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/$figureId': {
      id: '/figures/$figureId'
      path: '/figures/$figureId'
      fullPath: '/figures/$figureId'
      preLoaderRoute: typeof FiguresFigureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  ScanRoute: ScanRoute,
  WishlistRoute: WishlistRoute,
  ComicsComicIdRoute: ComicsComicIdRoute,
  FiguresFigureIdRoute: FiguresFigureIdRoute,
  ComicsIndexRoute: ComicsIndexRoute,
  FiguresIndexRoute: FiguresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
