// Generated by scripts/data_shards.py — do not edit.

import s00 from "./shards/00.json?raw";
import s01 from "./shards/01.json?raw";
import s02 from "./shards/02.json?raw";
import s03 from "./shards/03.json?raw";
import s04 from "./shards/04.json?raw";
import s05 from "./shards/05.json?raw";
import s06 from "./shards/06.json?raw";
import s07 from "./shards/07.json?raw";
import s08 from "./shards/08.json?raw";
import s09 from "./shards/09.json?raw";
import s0a from "./shards/0a.json?raw";
import s0b from "./shards/0b.json?raw";
import s0c from "./shards/0c.json?raw";
import s0d from "./shards/0d.json?raw";
import s0e from "./shards/0e.json?raw";
import s0f from "./shards/0f.json?raw";
import s10 from "./shards/10.json?raw";
import s11 from "./shards/11.json?raw";
import s12 from "./shards/12.json?raw";
import s13 from "./shards/13.json?raw";
import s14 from "./shards/14.json?raw";
import s15 from "./shards/15.json?raw";
import s16 from "./shards/16.json?raw";
import s17 from "./shards/17.json?raw";
import s18 from "./shards/18.json?raw";
import s19 from "./shards/19.json?raw";
import s1a from "./shards/1a.json?raw";
import s1b from "./shards/1b.json?raw";
import s1c from "./shards/1c.json?raw";
import s1d from "./shards/1d.json?raw";
import s1e from "./shards/1e.json?raw";
import s1f from "./shards/1f.json?raw";
import s20 from "./shards/20.json?raw";
import s21 from "./shards/21.json?raw";
import s22 from "./shards/22.json?raw";
import s23 from "./shards/23.json?raw";
import s24 from "./shards/24.json?raw";
import s25 from "./shards/25.json?raw";
import s26 from "./shards/26.json?raw";
import s27 from "./shards/27.json?raw";
import s28 from "./shards/28.json?raw";
import s29 from "./shards/29.json?raw";
import s2a from "./shards/2a.json?raw";
import s2b from "./shards/2b.json?raw";
import s2c from "./shards/2c.json?raw";
import s2d from "./shards/2d.json?raw";
import s2e from "./shards/2e.json?raw";
import s2f from "./shards/2f.json?raw";
import s30 from "./shards/30.json?raw";
import s31 from "./shards/31.json?raw";
import s32 from "./shards/32.json?raw";
import s33 from "./shards/33.json?raw";
import s34 from "./shards/34.json?raw";
import s35 from "./shards/35.json?raw";
import s36 from "./shards/36.json?raw";
import s37 from "./shards/37.json?raw";
import s38 from "./shards/38.json?raw";
import s39 from "./shards/39.json?raw";
import s3a from "./shards/3a.json?raw";
import s3b from "./shards/3b.json?raw";
import s3c from "./shards/3c.json?raw";
import s3d from "./shards/3d.json?raw";
import s3e from "./shards/3e.json?raw";
import s3f from "./shards/3f.json?raw";

export const SHARDS = [
  JSON.parse(s00),
  JSON.parse(s01),
  JSON.parse(s02),
  JSON.parse(s03),
  JSON.parse(s04),
  JSON.parse(s05),
  JSON.parse(s06),
  JSON.parse(s07),
  JSON.parse(s08),
  JSON.parse(s09),
  JSON.parse(s0a),
  JSON.parse(s0b),
  JSON.parse(s0c),
  JSON.parse(s0d),
  JSON.parse(s0e),
  JSON.parse(s0f),
  JSON.parse(s10),
  JSON.parse(s11),
  JSON.parse(s12),
  JSON.parse(s13),
  JSON.parse(s14),
  JSON.parse(s15),
  JSON.parse(s16),
  JSON.parse(s17),
  JSON.parse(s18),
  JSON.parse(s19),
  JSON.parse(s1a),
  JSON.parse(s1b),
  JSON.parse(s1c),
  JSON.parse(s1d),
  JSON.parse(s1e),
  JSON.parse(s1f),
  JSON.parse(s20),
  JSON.parse(s21),
  JSON.parse(s22),
  JSON.parse(s23),
  JSON.parse(s24),
  JSON.parse(s25),
  JSON.parse(s26),
  JSON.parse(s27),
  JSON.parse(s28),
  JSON.parse(s29),
  JSON.parse(s2a),
  JSON.parse(s2b),
  JSON.parse(s2c),
  JSON.parse(s2d),
  JSON.parse(s2e),
  JSON.parse(s2f),
  JSON.parse(s30),
  JSON.parse(s31),
  JSON.parse(s32),
  JSON.parse(s33),
  JSON.parse(s34),
  JSON.parse(s35),
  JSON.parse(s36),
  JSON.parse(s37),
  JSON.parse(s38),
  JSON.parse(s39),
  JSON.parse(s3a),
  JSON.parse(s3b),
  JSON.parse(s3c),
  JSON.parse(s3d),
  JSON.parse(s3e),
  JSON.parse(s3f),
] as { entries: Record<string, Record<string, unknown>> }[];
